export const mockOrders = [
  {
    id: "o1",
    statusTitle: "Оформлен",
    progress: "2 из 2",
    orderNumber: "Заказ №42974781892",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781892",
    statusSubtitle: "Добавлен в реестр",
    itemsCount: 2,
    totalRub: 3720,
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 101,
        src: "/products/t-shirt-1.png",
        name: "Футболка Basic",
        size: "L",
        article: "TSH-101",
        priceRub: 1860,
      },
      {
        id: 102,
        src: "/products/t-shirt-2.png",
        name: "Футболка Basic",
        size: "L",
        article: "TSH-102",
        priceRub: 1860,
      },
    ],
    totals: {
      itemsLabel: "2 товара",
      totalRub: 3720,
      discountRub: -0,
      promocode: null,
      giftPointsRub: -0,
      shippingRub: 0,
      shippingFrom: "",
      finalRub: 3720,
    },
  },
  {
    id: "o2",
    statusTitle: "В пути",
    progress: "4 из 5",
    orderNumber: "Заказ №42974781892",
    itemsCount: 5,
    totalRub: 3720,
    items: [
      { src: "/products/t-shirt-1.png" },
      { src: "/products/t-shirt-2.png" },
      { src: "/products/shoes-1.png" },
      { src: "/products/shoes-2.png" },
      { src: "/products/t-shirt-1.png", muted: true },
    ],
  },
  {
    id: "o3",
    statusTitle: "В пути",
    progress: "4 из 5",
    orderNumber: "Заказ №42974781894",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781894",
    subtitle: "Отказ в выпуске посылки по причине отсутствия корректных...",
    statusSubtitle: "Поступили на таможню в России",
    itemsCount: 1,
    totalRub: 9119,
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 51,
        src: "/products/shoes-2.png",
        name: "Джинсы Carne Bollente x Balenciaga",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
    ],
    totals: {
      itemsLabel: "1 товар",
      totalRub: 9119,
      discountRub: -500,
      promocode: { code: "PROMO100", rub: -500 },
      giftPointsRub: -200,
      shippingRub: 250,
      shippingFrom: "Доставка с Оренбурга",
      finalRub: 8669,
    },
  },
  {
    id: "o4",
    statusTitle: "В пункте выдачи",
    progress: "4 из 5",
    orderNumber: "Заказ №42974781890",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781890",
    statusSubtitle: "Заберите заказ",
    barcode: { code: "P00 039 145 3409" },
    itemsCount: 5,
    totalRub: 184260,
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 31,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 32,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 33,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 34,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
        muted: true,
      },
      {
        id: 35,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
    ],
    totals: {
      itemsLabel: "5 товаров",
      totalRub: 184260,
      discountRub: -500,
      promocode: { code: "PROMO100", rub: -500 },
      giftPointsRub: -200,
      shippingRub: 250,
      shippingFrom: "Доставка с Оренбурга",
      finalRub: 170899,
    },
  },
  {
    id: "o5",
    statusTitle: "Отменён",
    orderNumber: "Заказ №42974781893",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781894",
    subtitle: "Нет в продаже",
    statusHint: "Деньги за товар вернутся в течении 2–3 дней",
    itemsCount: 5,
    totalRub: 184260,
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 11,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 12,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 13,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 14,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
        muted: true,
      },
      {
        id: 15,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
    ],
    totals: {
      itemsLabel: "5 товаров",
      totalRub: 184260,
      discountRub: -500,
      promocode: { code: "PROMO100", rub: -500 },
      giftPointsRub: -200,
      shippingRub: 250,
      shippingFrom: "Доставка с Оренбурга",
      finalRub: 170899,
    },
  },
  {
    id: "o6",
    statusTitle: "Отменён",
    progress: "2 из 2",
    orderNumber: "Заказ №42974781893",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781893",
    subtitle: "Срок хранения истёк",
    statusHint: "Деньги за заказ возвращены",
    itemsCount: 2,
    totalRub: 1715,
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 21,
        src: "/products/shoes-2.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 22,
        src: "/products/shoes-2.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
    ],
    totals: {
      itemsLabel: "2 товара",
      totalRub: 1715,
      discountRub: -0,
      promocode: null,
      giftPointsRub: -0,
      shippingRub: 0,
      shippingFrom: "",
      finalRub: 1715,
    },
  },
  {
    id: "o7",
    statusTitle: "Получен",
    progress: "1 из 2",
    orderNumber: "Заказ №42974781891",
    itemsCount: 2,
    totalRub: 13720,
    receivedAt: "20 апреля",
    orderDateTitle: "Заказ от 1 апреля",
    orderNumberShort: "№42974781894",
    pickupPoint: {
      title: "Пункт выдачи",
      address: "Москва, Никольская ул дом 17, стр 2",
      meta: "CDEK · 7 дней хранения",
    },
    recipient: {
      title: "Получатель",
      name: "Овечкин Александр Михайлович",
      meta: "+7 910 889-77-62 · Avalex@gmail.com",
    },
    items: [
      {
        id: 3,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 4,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
        muted: true,
      },
      {
        id: 5,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 6,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
      {
        id: 7,
        src: "/products/t-shirt-1.png",
        name: "Худи Carne Bollente",
        size: "L",
        article: "4465457",
        priceRub: 9119,
      },
    ],
    totals: {
      itemsLabel: "5 товаров",
      totalRub: 184260,
      discountRub: -500,
      promocode: { code: "PROMO100", rub: -500 },
      giftPointsRub: -200,
      shippingRub: 250,
      shippingFrom: "Доставка с Оренбурга",
      finalRub: 170899,
    },
    showRating: true,
  },
];

export function getMockOrderById(id) {
  return mockOrders.find((o) => String(o.id) === String(id)) ?? null;
}
