"""init

Revision ID: 31e789139629
Revises:
Create Date: 2026-04-10 12:41:07.992377

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e789139629"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_groups",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key (UUIDv7)"),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=False,
            comment="Machine-readable unique code (e.g. 'general', 'physical')",
        ),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Multilingual display name",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Display ordering among groups (lower = first)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_groups")),
    )
    op.create_index(
        "ix_attribute_groups_name_i18n_gin",
        "attribute_groups",
        ["name_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "uix_attribute_groups_code", "attribute_groups", ["code"], unique=True
    )
    op.create_table(
        "attribute_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_templates")),
        sa.UniqueConstraint("code", name=op.f("uq_attribute_templates_code")),
    )
    op.create_table(
        "brands",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key (UUIDv7 for time-sortable ordering)",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Brand display name"
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-safe identifier for routing",
        ),
        sa.Column(
            "logo_storage_object_id",
            sa.UUID(),
            nullable=True,
            comment="Reference to storage_objects.id in ImageBackend",
        ),
        sa.Column(
            "logo_url",
            sa.String(length=1024),
            nullable=True,
            comment="Cached public URL from the Storage module",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        comment="Brand directory for the catalog",
    )
    op.create_index(
        op.f("ix_brands_logo_storage_object_id"),
        "brands",
        ["logo_storage_object_id"],
        unique=False,
    )
    op.create_index("uix_brands_name", "brands", ["name"], unique=True)
    op.create_index("uix_brands_slug", "brands", ["slug"], unique=True)
    op.create_table(
        "countries",
        sa.Column(
            "alpha2",
            sa.String(length=2),
            nullable=False,
            comment="ISO 3166-1 Alpha-2 code (e.g. KZ)",
        ),
        sa.Column(
            "alpha3",
            sa.String(length=3),
            nullable=False,
            comment="ISO 3166-1 Alpha-3 code (e.g. KAZ)",
        ),
        sa.Column(
            "numeric",
            sa.String(length=3),
            nullable=False,
            comment="ISO 3166-1 Numeric code, zero-padded (e.g. 398)",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("alpha2", name=op.f("pk_countries")),
        sa.UniqueConstraint("alpha3", name=op.f("uq_countries_alpha3")),
        sa.UniqueConstraint("numeric", name=op.f("uq_countries_numeric")),
    )
    op.create_table(
        "currencies",
        sa.Column(
            "code",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 alpha-3 code (e.g. UZS, USD, EUR)",
        ),
        sa.Column(
            "numeric",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 numeric code, zero-padded (e.g. 840, 978)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Common English name (e.g. US Dollar)",
        ),
        sa.Column(
            "minor_unit",
            sa.SmallInteger(),
            nullable=True,
            comment="Decimal places (2 for USD, 0 for JPY, 3 for BHD, NULL for XXX)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Available for selection in UI / API",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in currency pickers",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
        sa.UniqueConstraint("numeric", name=op.f("uq_currencies_numeric")),
    )
    op.create_index("ix_currencies_active", "currencies", ["is_active"], unique=False)
    op.create_index("ix_currencies_name", "currencies", ["name"], unique=False)
    op.create_index("ix_currencies_numeric", "currencies", ["numeric"], unique=False)
    op.create_table(
        "failed_tasks",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key"),
        sa.Column(
            "task_name",
            sa.String(length=255),
            nullable=False,
            comment="TaskIQ task name",
        ),
        sa.Column(
            "task_id",
            sa.String(length=255),
            nullable=False,
            comment="TaskIQ message ID",
        ),
        sa.Column(
            "args",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Task arguments",
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Task labels (correlation_id, etc.)",
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=False, comment="Error message text"
        ),
        sa.Column(
            "retry_count",
            sa.Integer(),
            nullable=False,
            comment="Number of retry attempts executed",
        ),
        sa.Column(
            "failed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the final failure",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failed_tasks")),
    )
    op.create_table(
        "identities",
        sa.Column("id", sa.UUID(), nullable=False, comment="PK (UUIDv7)"),
        sa.Column(
            "primary_auth_method",
            sa.Enum(
                "LOCAL",
                "OIDC",
                "TELEGRAM",
                name="primaryauthmethod",
                metadata=MetaData(),
                native_enum=False,
                length=10,
            ),
            nullable=False,
            comment="Authentication method: LOCAL, OIDC, or TELEGRAM",
        ),
        sa.Column(
            "account_type",
            sa.String(length=10),
            server_default="CUSTOMER",
            nullable=False,
            comment="Account type: CUSTOMER or STAFF",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether identity can authenticate",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "deactivated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When the identity was deactivated",
        ),
        sa.Column(
            "deactivated_by",
            sa.UUID(),
            nullable=True,
            comment="Identity ID of admin who deactivated this identity (null=self)",
        ),
        sa.Column(
            "token_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="Incrementing version for instant JWT invalidation",
        ),
        sa.ForeignKeyConstraint(
            ["deactivated_by"],
            ["identities.id"],
            name=op.f("fk_identities_deactivated_by_identities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
        comment="Authentication identities (root entity for IAM)",
    )
    op.create_index(
        op.f("ix_identities_account_type"), "identities", ["account_type"], unique=False
    )
    op.create_index(
        op.f("ix_identities_is_active"), "identities", ["is_active"], unique=False
    )
    op.create_table(
        "languages",
        sa.Column(
            "code",
            sa.String(length=12),
            nullable=False,
            comment="IETF BCP 47 tag (e.g. uz-Latn, en, ru)",
        ),
        sa.Column(
            "iso639_1",
            sa.String(length=2),
            nullable=True,
            comment="ISO 639-1 alpha-2 (e.g. uz, ru, en)",
        ),
        sa.Column(
            "iso639_2",
            sa.String(length=3),
            nullable=True,
            comment="ISO 639-2/T alpha-3 (e.g. uzb, rus, eng)",
        ),
        sa.Column(
            "iso639_3",
            sa.String(length=3),
            nullable=True,
            comment="ISO 639-3 alpha-3 (e.g. uzb, kaa)",
        ),
        sa.Column(
            "script",
            sa.String(length=4),
            nullable=True,
            comment="ISO 15924 script code (e.g. Latn, Cyrl, Arab)",
        ),
        sa.Column(
            "name_en",
            sa.String(length=100),
            nullable=False,
            comment="English name (e.g. Uzbek (Latin))",
        ),
        sa.Column(
            "name_native",
            sa.String(length=100),
            nullable=False,
            comment="Endonym (e.g. Русский)",
        ),
        sa.Column(
            "direction",
            sa.String(length=3),
            server_default="ltr",
            nullable=False,
            comment="Text direction: ltr or rtl",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Available for selection in UI",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Default fallback language (exactly one True)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in language pickers",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_languages")),
    )
    op.create_index("ix_languages_active", "languages", ["is_active"], unique=False)
    op.create_index("ix_languages_iso639_1", "languages", ["iso639_1"], unique=False)
    op.create_table(
        "outbox_messages",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key (UUIDv7 for time-based sorting)",
        ),
        sa.Column(
            "aggregate_type",
            sa.String(length=255),
            nullable=False,
            comment="Source aggregate type (Brand, Order, ...)",
        ),
        sa.Column(
            "aggregate_id",
            sa.String(length=255),
            nullable=False,
            comment="Source aggregate ID",
        ),
        sa.Column(
            "event_type",
            sa.String(length=255),
            nullable=False,
            comment="Domain event name (BrandLogoConfirmedEvent, ...)",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Serialized event body",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the event was written to the outbox",
        ),
        sa.Column(
            "processed_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp of successful broker publication (NULL = pending)",
        ),
        sa.Column(
            "correlation_id",
            sa.String(length=64),
            nullable=True,
            comment="Trace correlation ID (HTTP request_id -> Outbox -> TaskIQ)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        "ix_outbox_processed_created",
        "outbox_messages",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "codename",
            sa.String(length=100),
            nullable=False,
            comment="Permission codename in resource:action format",
        ),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("codename", name=op.f("uq_permissions_codename")),
        comment="RBAC permissions (resource:action codenames)",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="System roles cannot be modified or deleted",
        ),
        sa.Column(
            "target_account_type",
            sa.String(length=10),
            nullable=True,
            comment="Account type this role targets: CUSTOMER, STAFF, or NULL (any)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
        comment="RBAC role definitions",
    )
    op.create_table(
        "subdivision_types",
        sa.Column(
            "code",
            sa.String(length=60),
            nullable=False,
            comment="ISO type token (e.g. PROVINCE, EMIRATE)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in type filters",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_subdivision_types")),
    )
    op.create_table(
        "attributes",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "group_id",
            sa.UUID(),
            nullable=True,
            comment="FK to attribute_groups; NULL when group is deleted without reassignment",
        ),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "data_type",
            sa.Enum(
                "STRING",
                "INTEGER",
                "FLOAT",
                "BOOLEAN",
                name="attribute_data_type_enum",
                metadata=MetaData(),
            ),
            server_default="STRING",
            nullable=False,
        ),
        sa.Column(
            "ui_type",
            sa.Enum(
                "TEXT_BUTTON",
                "COLOR_SWATCH",
                "DROPDOWN",
                "CHECKBOX",
                "RANGE_SLIDER",
                name="attribute_ui_type_enum",
                metadata=MetaData(),
            ),
            server_default="TEXT_BUTTON",
            nullable=False,
        ),
        sa.Column(
            "is_dictionary",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum(
                "PRODUCT", "VARIANT", name="attribute_level_enum", metadata=MetaData()
            ),
            server_default="PRODUCT",
            nullable=False,
            comment="Product-level or variant-level attribute",
        ),
        sa.Column(
            "is_filterable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Available as filter on storefront",
        ),
        sa.Column(
            "is_searchable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Participates in full-text search",
        ),
        sa.Column(
            "search_weight",
            sa.Integer(),
            server_default=sa.text("5"),
            nullable=False,
            comment="Search ranking priority (1-10)",
        ),
        sa.Column(
            "is_comparable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Shown in product comparison table",
        ),
        sa.Column(
            "is_visible_on_card",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Shown on product detail page",
        ),
        sa.Column(
            "validation_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Type-specific validation constraints (e.g. min_length, max_value)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "search_weight BETWEEN 1 AND 10",
            name=op.f("ck_attributes_ck_attributes_search_weight"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["attribute_groups.id"],
            name=op.f("fk_attributes_group_id_attribute_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributes")),
    )
    op.create_index(
        "ix_attributes_filterable",
        "attributes",
        ["is_filterable"],
        unique=False,
        postgresql_where=sa.text("is_filterable = true"),
    )
    op.create_index(
        op.f("ix_attributes_group_id"), "attributes", ["group_id"], unique=False
    )
    op.create_index(
        "ix_attributes_name_i18n_gin",
        "attributes",
        ["name_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("uix_attributes_code", "attributes", ["code"], unique=True)
    op.create_index("uix_attributes_slug", "attributes", ["slug"], unique=True)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("full_slug", sa.String(length=1000), nullable=False),
        sa.Column("level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column(
            "effective_template_id",
            sa.UUID(),
            nullable=True,
            comment="Computed: own template_id or inherited from nearest ancestor",
        ),
        sa.ForeignKeyConstraint(
            ["effective_template_id"],
            ["attribute_templates.id"],
            name=op.f("fk_categories_effective_template_id_attribute_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["attribute_templates.id"],
            name=op.f("fk_categories_template_id_attribute_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_effective_template_id"),
        "categories",
        ["effective_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_full_slug"), "categories", ["full_slug"], unique=False
    )
    op.create_index(
        "ix_categories_full_slug_ops",
        "categories",
        ["full_slug"],
        unique=False,
        postgresql_ops={"full_slug": "varchar_pattern_ops"},
    )
    op.create_index(op.f("ix_categories_level"), "categories", ["level"], unique=False)
    op.create_index(
        "ix_categories_level_sort", "categories", ["level", "sort_order"], unique=False
    )
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_index(
        op.f("ix_categories_sort_order"), "categories", ["sort_order"], unique=False
    )
    op.create_index(
        op.f("ix_categories_template_id"), "categories", ["template_id"], unique=False
    )
    op.create_index(
        "uix_categories_slug",
        "categories",
        ["parent_id", "slug"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "country_currencies",
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2 (ISO 3166-1)",
        ),
        sa.Column(
            "currency_code",
            sa.String(length=3),
            nullable=False,
            comment="FK -> currencies.code (ISO 4217)",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether this is the country's primary/official currency",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_country_currencies_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_country_currencies_currency_code_currencies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "country_code", "currency_code", name=op.f("pk_country_currencies")
        ),
    )
    op.create_index(
        "ix_country_currencies_currency_code",
        "country_currencies",
        ["currency_code"],
        unique=False,
    )
    op.create_table(
        "country_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Translated short name (e.g. Россия)",
        ),
        sa.Column(
            "official_name",
            sa.String(length=255),
            nullable=True,
            comment="Official name if different from short",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_country_translations_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_country_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_translations")),
        sa.UniqueConstraint("country_code", "lang_code", name="uq_country_lang"),
    )
    op.create_index(
        "ix_country_tr_lang", "country_translations", ["lang_code"], unique=False
    )
    op.create_index(
        "ix_country_tr_name", "country_translations", ["name"], unique=False
    )
    op.create_table(
        "currency_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "currency_code",
            sa.String(length=3),
            nullable=False,
            comment="FK -> currencies.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Translated currency name (e.g. Доллар США)",
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_currency_translations_currency_code_currencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_currency_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency_translations")),
        sa.UniqueConstraint("currency_code", "lang_code", name="uq_currency_lang"),
    )
    op.create_index(
        "ix_currency_tr_lang", "currency_translations", ["lang_code"], unique=False
    )
    op.create_index(
        "ix_currency_tr_name", "currency_translations", ["name"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_email", sa.String(length=320), nullable=True),
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("referral_code", sa.String(length=12), nullable=True),
        sa.Column("referred_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["identities.id"],
            name=op.f("fk_customers_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["customers.id"],
            name=op.f("fk_customers_referred_by_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("referral_code", name=op.f("uq_customers_referral_code")),
        comment="Customer profiles with referral data (GDPR-isolated)",
    )
    op.create_table(
        "identity_roles",
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "assigned_by",
            sa.UUID(),
            nullable=True,
            comment="Identity ID of admin who assigned this role",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identities.id"],
            name=op.f("fk_identity_roles_assigned_by_identities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_identity_roles_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_identity_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "identity_id", "role_id", name=op.f("pk_identity_roles")
        ),
    )
    op.create_index(
        "ix_identity_roles_identity_id", "identity_roles", ["identity_id"], unique=False
    )
    op.create_index(
        "ix_identity_roles_role_id", "identity_roles", ["role_id"], unique=False
    )
    op.create_table(
        "linked_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_sub_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=320), nullable=True),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether provider verified this email",
        ),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Provider-specific profile data",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_linked_accounts_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_linked_accounts")),
        sa.UniqueConstraint(
            "provider", "provider_sub_id", name="uq_linked_accounts_provider_sub"
        ),
        comment="External OIDC provider accounts linked to identities",
    )
    op.create_index(
        op.f("ix_linked_accounts_identity_id"),
        "linked_accounts",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "local_credentials",
        sa.Column(
            "identity_id",
            sa.UUID(),
            nullable=False,
            comment="PK + FK -> identities (Shared PK 1:1)",
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="Login email (unique across system)",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=512),
            nullable=False,
            comment="Argon2id (new) or Bcrypt (legacy) hash — 512 for non-default Argon2 params",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_local_credentials_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("identity_id", name=op.f("pk_local_credentials")),
        sa.UniqueConstraint("email", name=op.f("uq_local_credentials_email")),
        comment="Local auth credentials (email + password hash)",
    )
    op.create_table(
        "role_hierarchy",
        sa.Column("parent_role_id", sa.UUID(), nullable=False),
        sa.Column("child_role_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "parent_role_id != child_role_id",
            name=op.f("ck_role_hierarchy_ck_role_hierarchy_no_self_ref"),
        ),
        sa.ForeignKeyConstraint(
            ["child_role_id"],
            ["roles.id"],
            name=op.f("fk_role_hierarchy_child_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["roles.id"],
            name=op.f("fk_role_hierarchy_parent_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "parent_role_id", "child_role_id", name=op.f("pk_role_hierarchy")
        ),
        comment="Role inheritance: parent inherits all child permissions via CTE",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name=op.f("pk_role_permissions")
        ),
    )
    op.create_index(
        "ix_role_permissions_role_id", "role_permissions", ["role_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column(
            "refresh_token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of opaque refresh token",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="Client IP at session creation",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="Client User-Agent",
        ),
        sa.Column(
            "is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Refresh token expiry (created_at + REFRESH_TOKEN_EXPIRE_DAYS)",
        ),
        sa.Column(
            "last_active_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last token refresh timestamp",
        ),
        sa.Column(
            "idle_expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Sliding idle timeout (extends on refresh)",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_sessions_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint(
            "refresh_token_hash", name=op.f("uq_sessions_refresh_token_hash")
        ),
        comment="Authentication sessions with refresh token rotation",
    )
    op.create_index(
        "ix_sessions_identity_active",
        "sessions",
        ["identity_id", "is_revoked", "expires_at"],
        unique=False,
    )
    op.create_table(
        "staff_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=10), server_default="PENDING", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("accepted_identity_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_identity_id"],
            ["identities.id"],
            name=op.f("fk_staff_invitations_accepted_identity_id_identities"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["identities.id"],
            name=op.f("fk_staff_invitations_invited_by_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_staff_invitations_token_hash")),
        comment="Staff member invitations with token-based acceptance",
    )
    op.create_index(
        op.f("ix_staff_invitations_email"), "staff_invitations", ["email"], unique=False
    )
    op.create_index(
        "ix_staff_invitations_email_status",
        "staff_invitations",
        ["email", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_staff_invitations_status"),
        "staff_invitations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "staff_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("profile_email", sa.String(length=320), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["identities.id"],
            name=op.f("fk_staff_members_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["identities.id"],
            name=op.f("fk_staff_members_invited_by_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_members")),
        comment="Staff member profiles",
    )
    op.create_table(
        "subdivision_type_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "type_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> subdivision_types.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Translated label (e.g. Область, Province)",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_subdivision_type_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["subdivision_types.code"],
            name=op.f("fk_subdivision_type_translations_type_code_subdivision_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subdivision_type_translations")),
        sa.UniqueConstraint("type_code", "lang_code", name="uq_sub_type_lang"),
    )
    op.create_index(
        "ix_sub_type_tr_lang",
        "subdivision_type_translations",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "subdivisions",
        sa.Column(
            "code",
            sa.String(length=10),
            nullable=False,
            comment="ISO 3166-2 code (e.g. RU-MOW, UZ-TO)",
        ),
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2",
        ),
        sa.Column(
            "type_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> subdivision_types.code",
        ),
        sa.Column(
            "parent_code",
            sa.String(length=10),
            nullable=True,
            comment="Parent subdivision for nested levels",
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid latitude (WGS 84)",
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid longitude (WGS 84)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order within parent country",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Soft-delete / visibility flag",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_subdivisions_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_code"],
            ["subdivisions.code"],
            name=op.f("fk_subdivisions_parent_code_subdivisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["subdivision_types.code"],
            name=op.f("fk_subdivisions_type_code_subdivision_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_subdivisions")),
    )
    op.create_index(
        "ix_subdivisions_country", "subdivisions", ["country_code"], unique=False
    )
    op.create_index(
        "ix_subdivisions_parent", "subdivisions", ["parent_code"], unique=False
    )
    op.create_index(
        "ix_subdivisions_type",
        "subdivisions",
        ["country_code", "type_code"],
        unique=False,
    )
    op.create_table(
        "attribute_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "value_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "search_aliases",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("value_group", sa.String(length=100), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Inactive values hidden from storefront but preserved on existing products",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_attribute_values_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_values")),
    )
    op.create_index(
        "ix_attr_val_active",
        "attribute_values",
        ["attribute_id", "sort_order"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "ix_attr_val_search_aliases_gin",
        "attribute_values",
        ["search_aliases"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_attr_val_value_i18n_gin",
        "attribute_values",
        ["value_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_attribute_values_attribute_id"),
        "attribute_values",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_values_slug"), "attribute_values", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_attribute_values_value_group"),
        "attribute_values",
        ["value_group"],
        unique=False,
    )
    op.create_index(
        "uix_attr_val_code", "attribute_values", ["attribute_id", "code"], unique=True
    )
    op.create_index(
        "uix_attr_val_slug", "attribute_values", ["attribute_id", "slug"], unique=True
    )
    op.create_table(
        "session_roles",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_session_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_roles_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "role_id", name=op.f("pk_session_roles")),
    )
    op.create_table(
        "staff_invitation_roles",
        sa.Column("invitation_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["staff_invitations.id"],
            name=op.f("fk_staff_invitation_roles_invitation_id_staff_invitations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_staff_invitation_roles_role_id_roles"),
        ),
        sa.PrimaryKeyConstraint(
            "invitation_id", "role_id", name=op.f("pk_staff_invitation_roles")
        ),
    )
    op.create_table(
        "subdivision_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "subdivision_code",
            sa.String(length=10),
            nullable=False,
            comment="FK -> subdivisions.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Translated name (e.g. Москва, Moscow)",
        ),
        sa.Column(
            "official_name",
            sa.String(length=255),
            nullable=True,
            comment="Full official name if different from short",
        ),
        sa.Column(
            "local_variant",
            sa.String(length=255),
            nullable=True,
            comment="Alternative / local name (e.g. Yugra for KhMAO)",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_subdivision_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subdivision_code"],
            ["subdivisions.code"],
            name=op.f("fk_subdivision_translations_subdivision_code_subdivisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subdivision_translations")),
        sa.UniqueConstraint(
            "subdivision_code", "lang_code", name="uq_subdivision_lang"
        ),
    )
    op.create_index(
        "ix_sub_tr_lang", "subdivision_translations", ["lang_code"], unique=False
    )
    op.create_index(
        "ix_sub_tr_name", "subdivision_translations", ["name"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CROSS_BORDER", "LOCAL", name="supplier_type_enum", metadata=MetaData()
            ),
            nullable=False,
        ),
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="ISO 3166-1 alpha-2 country code",
        ),
        sa.Column(
            "subdivision_code",
            sa.String(length=10),
            nullable=True,
            comment="ISO 3166-2 subdivision code (optional)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_suppliers_country_code_countries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subdivision_code"],
            ["subdivisions.code"],
            name=op.f("fk_suppliers_subdivision_code_subdivisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index(
        "ix_suppliers_country_code", "suppliers", ["country_code"], unique=False
    )
    op.create_table(
        "template_attribute_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "requirement_level",
            sa.Enum(
                "REQUIRED",
                "RECOMMENDED",
                "OPTIONAL",
                name="requirement_level_enum",
                metadata=MetaData(),
            ),
            server_default="OPTIONAL",
            nullable=False,
        ),
        sa.Column(
            "filter_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_template_attribute_bindings_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["attribute_templates.id"],
            name=op.f("fk_template_attribute_bindings_template_id_attribute_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_attribute_bindings")),
        sa.UniqueConstraint(
            "template_id", "attribute_id", name="uix_template_attr_binding"
        ),
    )
    op.create_index(
        op.f("ix_template_attribute_bindings_attribute_id"),
        "template_attribute_bindings",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_attribute_bindings_template_id"),
        "template_attribute_bindings",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("primary_category_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "title_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "popularity_score",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("country_of_origin", sa.String(length=2), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ENRICHING",
                "READY_FOR_REVIEW",
                "PUBLISHED",
                "ARCHIVED",
                name="product_status_enum",
                metadata=MetaData(),
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "is_visible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_category_id"],
            ["categories.id"],
            name=op.f("fk_products_primary_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_products_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "ix_products_attributes_gin",
        "products",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False
    )
    op.create_index(
        "ix_products_catalog_listing",
        "products",
        ["brand_id", "primary_category_id", "status", "popularity_score"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.create_index(
        op.f("ix_products_deleted_at"), "products", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_products_primary_category_id"),
        "products",
        ["primary_category_id"],
        unique=False,
    )
    op.create_index(
        "ix_products_published_at",
        "products",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND published_at IS NOT NULL"),
    )
    op.create_index(
        "ix_products_sale_listing",
        "products",
        ["brand_id", "primary_category_id", "popularity_score"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_index(
        op.f("ix_products_supplier_id"), "products", ["supplier_id"], unique=False
    )
    op.create_index(
        "ix_products_tags_gin",
        "products",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_products_title_gin",
        "products",
        ["title_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "uix_products_slug",
        "products",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "product_attribute_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("attribute_value_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_product_attribute_values_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_values.id"],
            name=op.f(
                "fk_product_attribute_values_attribute_value_id_attribute_values"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_attribute_values_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_attribute_values")),
        sa.UniqueConstraint(
            "product_id", "attribute_id", name="uix_product_single_attribute_value"
        ),
    )
    op.create_index(
        "ix_product_attr_val_lookup",
        "product_attribute_values",
        ["attribute_value_id", "product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_attribute_values_attribute_id"),
        "product_attribute_values",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_attribute_values_attribute_value_id"),
        "product_attribute_values",
        ["attribute_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_attribute_values_product_id"),
        "product_attribute_values",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "default_price",
            sa.Integer(),
            nullable=True,
            comment="Default price in smallest currency units",
        ),
        sa.Column(
            "default_currency",
            sa.String(length=3),
            server_default=sa.text("'RUB'"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_currency"],
            ["currencies.code"],
            name=op.f("fk_product_variants_default_currency_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
    )
    op.create_index(
        op.f("ix_product_variants_deleted_at"),
        "product_variants",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_variants_product_id",
        "product_variants",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column(
            "media_type",
            sa.Enum(
                "IMAGE",
                "VIDEO",
                "MODEL_3D",
                "DOCUMENT",
                name="media_type_enum",
                metadata=MetaData(),
            ),
            server_default="IMAGE",
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "MAIN",
                "HOVER",
                "GALLERY",
                "HERO_VIDEO",
                "SIZE_GUIDE",
                "PACKAGING",
                name="media_role_enum",
                metadata=MetaData(),
            ),
            server_default="GALLERY",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "storage_object_id",
            sa.UUID(),
            nullable=True,
            comment="Reference to storage_objects.id (unified file registry)",
        ),
        sa.Column(
            "is_external",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="True when the resource is hosted externally (not in our S3)",
        ),
        sa.Column(
            "url",
            sa.String(length=1024),
            nullable=True,
            comment="Public URL of the media asset",
        ),
        sa.Column(
            "image_variants",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Image size variants: [{size, width, height, url}, ...]",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_media_assets_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_media_assets_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        op.f("ix_media_assets_media_type"), "media_assets", ["media_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_product_id"), "media_assets", ["product_id"], unique=False
    )
    op.create_index(
        "ix_media_assets_product_variant_sort",
        "media_assets",
        ["product_id", "variant_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_storage_object_id"),
        "media_assets",
        ["storage_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_variant_id"), "media_assets", ["variant_id"], unique=False
    )
    op.create_index(
        "uix_media_single_main_per_variant",
        "media_assets",
        ["product_id", "variant_id"],
        unique=True,
        postgresql_where=sa.text("role = 'MAIN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("sku_code", sa.String(length=100), nullable=False),
        sa.Column("variant_hash", sa.String(length=64), nullable=False),
        sa.Column("main_image_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "attributes_cache",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "price",
            sa.Integer(),
            nullable=True,
            comment="Base price in smallest currency units (e.g. kopecks), nullable — inherits from variant",
        ),
        sa.Column(
            "compare_at_price",
            sa.Integer(),
            nullable=True,
            comment="Previous price for strikethrough display",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'RUB'"),
            nullable=False,
            comment="ISO 4217 currency code (FK → geo.currencies)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
            name=op.f("fk_skus_currency_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_skus_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_skus_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index(op.f("ix_skus_deleted_at"), "skus", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_index(op.f("ix_skus_variant_id"), "skus", ["variant_id"], unique=False)
    op.create_index(
        "uix_skus_sku_code",
        "skus",
        ["sku_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uix_skus_variant_hash",
        "skus",
        ["variant_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "sku_attribute_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("attribute_value_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_sku_attribute_values_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_values.id"],
            name=op.f("fk_sku_attribute_values_attribute_value_id_attribute_values"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_sku_attribute_values_sku_id_skus"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_attribute_values")),
        sa.UniqueConstraint(
            "sku_id", "attribute_id", name="uix_sku_single_attribute_value"
        ),
    )
    op.create_index(
        "ix_sku_attr_val_lookup",
        "sku_attribute_values",
        ["attribute_value_id", "sku_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_attribute_id"),
        "sku_attribute_values",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_attribute_value_id"),
        "sku_attribute_values",
        ["attribute_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_sku_id"),
        "sku_attribute_values",
        ["sku_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sku_attribute_values_sku_id"), table_name="sku_attribute_values"
    )
    op.drop_index(
        op.f("ix_sku_attribute_values_attribute_value_id"),
        table_name="sku_attribute_values",
    )
    op.drop_index(
        op.f("ix_sku_attribute_values_attribute_id"), table_name="sku_attribute_values"
    )
    op.drop_index("ix_sku_attr_val_lookup", table_name="sku_attribute_values")
    op.drop_table("sku_attribute_values")
    op.drop_index(
        "uix_skus_variant_hash",
        table_name="skus",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uix_skus_sku_code",
        table_name="skus",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_skus_variant_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_deleted_at"), table_name="skus")
    op.drop_table("skus")
    op.drop_index(
        "uix_media_single_main_per_variant",
        table_name="media_assets",
        postgresql_where=sa.text("role = 'MAIN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_media_assets_variant_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_storage_object_id"), table_name="media_assets")
    op.drop_index("ix_media_assets_product_variant_sort", table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_product_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_media_type"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("ix_product_variants_product_id", table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_deleted_at"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(
        op.f("ix_product_attribute_values_product_id"),
        table_name="product_attribute_values",
    )
    op.drop_index(
        op.f("ix_product_attribute_values_attribute_value_id"),
        table_name="product_attribute_values",
    )
    op.drop_index(
        op.f("ix_product_attribute_values_attribute_id"),
        table_name="product_attribute_values",
    )
    op.drop_index("ix_product_attr_val_lookup", table_name="product_attribute_values")
    op.drop_table("product_attribute_values")
    op.drop_index(
        "uix_products_slug",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_products_title_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_index("ix_products_tags_gin", table_name="products", postgresql_using="gin")
    op.drop_index(op.f("ix_products_supplier_id"), table_name="products")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(
        "ix_products_sale_listing",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.drop_index(
        "ix_products_published_at",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL AND published_at IS NOT NULL"),
    )
    op.drop_index(op.f("ix_products_primary_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_deleted_at"), table_name="products")
    op.drop_index(
        "ix_products_catalog_listing",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_index(
        "ix_products_attributes_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_table("products")
    op.drop_index(
        op.f("ix_template_attribute_bindings_template_id"),
        table_name="template_attribute_bindings",
    )
    op.drop_index(
        op.f("ix_template_attribute_bindings_attribute_id"),
        table_name="template_attribute_bindings",
    )
    op.drop_table("template_attribute_bindings")
    op.drop_index("ix_suppliers_country_code", table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("ix_sub_tr_name", table_name="subdivision_translations")
    op.drop_index("ix_sub_tr_lang", table_name="subdivision_translations")
    op.drop_table("subdivision_translations")
    op.drop_table("staff_invitation_roles")
    op.drop_table("session_roles")
    op.drop_index("uix_attr_val_slug", table_name="attribute_values")
    op.drop_index("uix_attr_val_code", table_name="attribute_values")
    op.drop_index(
        op.f("ix_attribute_values_value_group"), table_name="attribute_values"
    )
    op.drop_index(op.f("ix_attribute_values_slug"), table_name="attribute_values")
    op.drop_index(
        op.f("ix_attribute_values_attribute_id"), table_name="attribute_values"
    )
    op.drop_index(
        "ix_attr_val_value_i18n_gin",
        table_name="attribute_values",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_attr_val_search_aliases_gin",
        table_name="attribute_values",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_attr_val_active",
        table_name="attribute_values",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("attribute_values")
    op.drop_index("ix_subdivisions_type", table_name="subdivisions")
    op.drop_index("ix_subdivisions_parent", table_name="subdivisions")
    op.drop_index("ix_subdivisions_country", table_name="subdivisions")
    op.drop_table("subdivisions")
    op.drop_index("ix_sub_type_tr_lang", table_name="subdivision_type_translations")
    op.drop_table("subdivision_type_translations")
    op.drop_table("staff_members")
    op.drop_index(op.f("ix_staff_invitations_status"), table_name="staff_invitations")
    op.drop_index("ix_staff_invitations_email_status", table_name="staff_invitations")
    op.drop_index(op.f("ix_staff_invitations_email"), table_name="staff_invitations")
    op.drop_table("staff_invitations")
    op.drop_index("ix_sessions_identity_active", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_role_permissions_role_id", table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_table("role_hierarchy")
    op.drop_table("local_credentials")
    op.drop_index(op.f("ix_linked_accounts_identity_id"), table_name="linked_accounts")
    op.drop_table("linked_accounts")
    op.drop_index("ix_identity_roles_role_id", table_name="identity_roles")
    op.drop_index("ix_identity_roles_identity_id", table_name="identity_roles")
    op.drop_table("identity_roles")
    op.drop_table("customers")
    op.drop_index("ix_currency_tr_name", table_name="currency_translations")
    op.drop_index("ix_currency_tr_lang", table_name="currency_translations")
    op.drop_table("currency_translations")
    op.drop_index("ix_country_tr_name", table_name="country_translations")
    op.drop_index("ix_country_tr_lang", table_name="country_translations")
    op.drop_table("country_translations")
    op.drop_index(
        "ix_country_currencies_currency_code", table_name="country_currencies"
    )
    op.drop_table("country_currencies")
    op.drop_index(
        "uix_categories_slug",
        table_name="categories",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_categories_template_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_sort_order"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index("ix_categories_level_sort", table_name="categories")
    op.drop_index(op.f("ix_categories_level"), table_name="categories")
    op.drop_index(
        "ix_categories_full_slug_ops",
        table_name="categories",
        postgresql_ops={"full_slug": "varchar_pattern_ops"},
    )
    op.drop_index(op.f("ix_categories_full_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_effective_template_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index("uix_attributes_slug", table_name="attributes")
    op.drop_index("uix_attributes_code", table_name="attributes")
    op.drop_index(
        "ix_attributes_name_i18n_gin", table_name="attributes", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_attributes_group_id"), table_name="attributes")
    op.drop_index(
        "ix_attributes_filterable",
        table_name="attributes",
        postgresql_where=sa.text("is_filterable = true"),
    )
    op.drop_table("attributes")
    op.drop_table("subdivision_types")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index("ix_outbox_processed_created", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index("ix_languages_iso639_1", table_name="languages")
    op.drop_index("ix_languages_active", table_name="languages")
    op.drop_table("languages")
    op.drop_index(op.f("ix_identities_is_active"), table_name="identities")
    op.drop_index(op.f("ix_identities_account_type"), table_name="identities")
    op.drop_table("identities")
    op.drop_table("failed_tasks")
    op.drop_index("ix_currencies_numeric", table_name="currencies")
    op.drop_index("ix_currencies_name", table_name="currencies")
    op.drop_index("ix_currencies_active", table_name="currencies")
    op.drop_table("currencies")
    op.drop_table("countries")
    op.drop_index("uix_brands_slug", table_name="brands")
    op.drop_index("uix_brands_name", table_name="brands")
    op.drop_index(op.f("ix_brands_logo_storage_object_id"), table_name="brands")
    op.drop_table("brands")
    op.drop_table("attribute_templates")
    op.drop_index("uix_attribute_groups_code", table_name="attribute_groups")
    op.drop_index(
        "ix_attribute_groups_name_i18n_gin",
        table_name="attribute_groups",
        postgresql_using="gin",
    )
    op.drop_table("attribute_groups")
    # ### end Alembic commands ###
