"""add cart module tables

Revision ID: 289970c60fc2
Revises: 58c349468552
Create Date: 2026-04-12 21:31:13.589300

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "289970c60fc2"
down_revision: str | Sequence[str] | None = "58c349468552"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=True),
        sa.Column("anonymous_token", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("frozen_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_repriced_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'frozen', 'merged', 'ordered')",
            name=op.f("ck_carts_valid_status"),
        ),
        sa.CheckConstraint(
            "(identity_id IS NOT NULL AND anonymous_token IS NULL) OR (identity_id IS NULL AND anonymous_token IS NOT NULL)",
            name=op.f("ck_carts_owner_xor"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
        comment="Shopping carts with lifecycle FSM",
    )
    op.create_index(
        op.f("ix_carts_identity_id"), "carts", ["identity_id"], unique=False
    )
    op.create_index(
        "uix_carts_anonymous_active",
        "carts",
        ["anonymous_token"],
        unique=True,
        postgresql_where="status = 'active' AND anonymous_token IS NOT NULL",
    )
    op.create_index(
        "uix_carts_identity_active",
        "carts",
        ["identity_id"],
        unique=True,
        postgresql_where="status = 'active' AND identity_id IS NOT NULL",
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_type", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0 AND quantity <= 99", name=op.f("ck_cart_items_valid_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
            name=op.f("fk_cart_items_cart_id_carts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        comment="Cart line items (one per SKU per cart)",
    )
    op.create_index(
        op.f("ix_cart_items_sku_id"), "cart_items", ["sku_id"], unique=False
    )
    op.create_index(
        "uix_cart_items_cart_sku", "cart_items", ["cart_id", "sku_id"], unique=True
    )
    op.create_table(
        "checkout_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column(
            "items_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Serialized CheckoutItemSnapshot[]",
        ),
        sa.Column("pickup_point_id", sa.UUID(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
            name=op.f("fk_checkout_snapshots_cart_id_carts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_snapshots")),
        comment="Frozen price snapshots for checkout validation",
    )
    op.create_index(
        op.f("ix_checkout_snapshots_cart_id"),
        "checkout_snapshots",
        ["cart_id"],
        unique=False,
    )
    op.create_table(
        "checkout_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'cancelled', 'expired', 'failed')",
            name=op.f("ck_checkout_attempts_valid_attempt_status"),
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
            name=op.f("fk_checkout_attempts_cart_id_carts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["checkout_snapshots.id"],
            name=op.f("fk_checkout_attempts_snapshot_id_checkout_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_attempts")),
        comment="Checkout attempts with at-most-one pending per cart",
    )
    op.create_index(
        op.f("ix_checkout_attempts_cart_id"),
        "checkout_attempts",
        ["cart_id"],
        unique=False,
    )
    op.create_index(
        "uix_checkout_attempts_cart_pending",
        "checkout_attempts",
        ["cart_id"],
        unique=True,
        postgresql_where="status = 'pending'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_checkout_attempts_cart_pending",
        table_name="checkout_attempts",
        postgresql_where="status = 'pending'",
    )
    op.drop_index(op.f("ix_checkout_attempts_cart_id"), table_name="checkout_attempts")
    op.drop_table("checkout_attempts")
    op.drop_index(
        op.f("ix_checkout_snapshots_cart_id"), table_name="checkout_snapshots"
    )
    op.drop_table("checkout_snapshots")
    op.drop_index("uix_cart_items_cart_sku", table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_sku_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(
        "uix_carts_identity_active",
        table_name="carts",
        postgresql_where="status = 'active' AND identity_id IS NOT NULL",
    )
    op.drop_index(
        "uix_carts_anonymous_active",
        table_name="carts",
        postgresql_where="status = 'active' AND anonymous_token IS NOT NULL",
    )
    op.drop_index(op.f("ix_carts_identity_id"), table_name="carts")
    op.drop_table("carts")
    # ### end Alembic commands ###
