"""add pricing_variables

Revision ID: 2155d2aa4f87
Revises: 3137281095e0
Create Date: 2026-04-20 11:50:29.644477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2155d2aa4f87"
down_revision: str | Sequence[str] | None = "3137281095e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_variables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("data_type", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("default_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_fx_rate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "is_user_editable_at_runtime",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("max_age_days", sa.Integer(), nullable=True),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_type IN ('decimal', 'integer', 'percent')",
            name=op.f("ck_pricing_variables_ck_pricing_variables_valid_data_type"),
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'supplier', 'category', 'range', 'product_input')",
            name=op.f("ck_pricing_variables_ck_pricing_variables_valid_scope"),
        ),
        sa.CheckConstraint(
            "(is_fx_rate = false AND max_age_days IS NULL) OR (is_fx_rate = true AND max_age_days BETWEEN 1 AND 365)",
            name=op.f("ck_pricing_variables_ck_pricing_variables_fx_age"),
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f("ck_pricing_variables_ck_pricing_variables_version_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_variables")),
        sa.UniqueConstraint("code", name="uq_pricing_variables_code"),
        comment="Pricing variable registry (FRD §Variable)",
    )
    op.create_index(
        op.f("ix_pricing_variables_is_fx_rate"),
        "pricing_variables",
        ["is_fx_rate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_variables_is_system"),
        "pricing_variables",
        ["is_system"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_variables_scope"), "pricing_variables", ["scope"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pricing_variables_scope"), table_name="pricing_variables")
    op.drop_index(
        op.f("ix_pricing_variables_is_system"), table_name="pricing_variables"
    )
    op.drop_index(
        op.f("ix_pricing_variables_is_fx_rate"), table_name="pricing_variables"
    )
    op.drop_table("pricing_variables")
    # ### end Alembic commands ###
