"""add pricing_contexts

Revision ID: 496299a82596
Revises: 2155d2aa4f87
Create Date: 2026-04-20 12:05:59.134377

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "496299a82596"
down_revision: str | Sequence[str] | None = "2155d2aa4f87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_frozen", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("freeze_reason", sa.String(length=1024), nullable=True),
        sa.Column(
            "rounding_mode",
            sa.String(length=16),
            server_default="HALF_UP",
            nullable=False,
        ),
        sa.Column("rounding_step", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("margin_floor_pct", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "evaluation_timeout_ms", sa.Integer(), server_default="50", nullable=False
        ),
        sa.Column(
            "simulation_threshold", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "approval_required_on_publish",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("range_base_variable_code", sa.String(length=64), nullable=True),
        sa.Column("active_formula_version_id", sa.UUID(), nullable=True),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rounding_mode IN ('HALF_UP', 'HALF_EVEN', 'CEILING', 'FLOOR')",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_valid_rounding_mode"),
        ),
        sa.CheckConstraint(
            "(is_frozen = false AND freeze_reason IS NULL) OR (is_frozen = true AND freeze_reason IS NOT NULL)",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_freeze_consistency"),
        ),
        sa.CheckConstraint(
            "evaluation_timeout_ms BETWEEN 1 AND 60000",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_timeout_range"),
        ),
        sa.CheckConstraint(
            "margin_floor_pct BETWEEN 0 AND 1",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_margin_floor_pct_range"),
        ),
        sa.CheckConstraint(
            "rounding_step > 0",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_rounding_step_positive"),
        ),
        sa.CheckConstraint(
            "simulation_threshold >= 0",
            name=op.f(
                "ck_pricing_contexts_ck_pricing_contexts_sim_threshold_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f("ck_pricing_contexts_ck_pricing_contexts_version_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_contexts")),
        sa.UniqueConstraint("code", name="uq_pricing_contexts_code"),
        comment="Pricing context registry (FRD §Contexts)",
    )
    op.create_index(
        op.f("ix_pricing_contexts_is_active"),
        "pricing_contexts",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_contexts_is_frozen"),
        "pricing_contexts",
        ["is_frozen"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pricing_contexts_is_frozen"), table_name="pricing_contexts")
    op.drop_index(op.f("ix_pricing_contexts_is_active"), table_name="pricing_contexts")
    op.drop_table("pricing_contexts")
    # ### end Alembic commands ###
