"""add_pricing_formula_versions

Revision ID: 07cd330ed345
Revises: 496299a82596
Create Date: 2026-04-20 12:18:34.929234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07cd330ed345"
down_revision: str | Sequence[str] | None = "496299a82596"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_formula_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ast", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'draft' AND published_at IS NULL AND published_by IS NULL) OR (status IN ('published', 'archived') AND published_at IS NOT NULL)",
            name=op.f(
                "ck_pricing_formula_versions_ck_pricing_formula_published_fields_consistency"
            ),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_pricing_formula_versions_ck_pricing_formula_valid_status"),
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f(
                "ck_pricing_formula_versions_ck_pricing_formula_version_lock_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "version_number >= 1",
            name=op.f(
                "ck_pricing_formula_versions_ck_pricing_formula_version_number_positive"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_formula_versions")),
        comment="Pricing formula versions (FRD §FormulaVersion)",
    )
    op.create_index(
        op.f("ix_pricing_formula_versions_context_id"),
        "pricing_formula_versions",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_formula_versions_status"),
        "pricing_formula_versions",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_pricing_formula_draft_per_context",
        "pricing_formula_versions",
        ["context_id"],
        unique=True,
        postgresql_where="status = 'draft'",
    )
    op.create_index(
        "uq_pricing_formula_published_per_context",
        "pricing_formula_versions",
        ["context_id"],
        unique=True,
        postgresql_where="status = 'published'",
    )
    op.create_index(
        "uq_pricing_formula_version_number_per_context",
        "pricing_formula_versions",
        ["context_id", "version_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pricing_formula_version_number_per_context",
        table_name="pricing_formula_versions",
    )
    op.drop_index(
        "uq_pricing_formula_published_per_context",
        table_name="pricing_formula_versions",
        postgresql_where="status = 'published'",
    )
    op.drop_index(
        "uq_pricing_formula_draft_per_context",
        table_name="pricing_formula_versions",
        postgresql_where="status = 'draft'",
    )
    op.drop_index(
        op.f("ix_pricing_formula_versions_status"),
        table_name="pricing_formula_versions",
    )
    op.drop_index(
        op.f("ix_pricing_formula_versions_context_id"),
        table_name="pricing_formula_versions",
    )
    op.drop_table("pricing_formula_versions")
    # ### end Alembic commands ###
