"""add pricing product pricing profiles table

Revision ID: 3137281095e0
Revises: 4981af74792a
Create Date: 2026-04-20 10:11:36.674715

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3137281095e0"
down_revision: str | Sequence[str] | None = "4981af74792a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_product_pricing_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column(
            "values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'ready', 'stale')",
            name=op.f(
                "ck_pricing_product_pricing_profiles_ck_pricing_profiles_valid_status"
            ),
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f(
                "ck_pricing_product_pricing_profiles_ck_pricing_profiles_version_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_product_pricing_profiles")),
        comment="scope=product_input values per product (ADR-004)",
    )
    op.create_index(
        op.f("ix_pricing_product_pricing_profiles_context_id"),
        "pricing_product_pricing_profiles",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        "uq_pricing_profiles_product_active",
        "pricing_product_pricing_profiles",
        ["product_id"],
        unique=True,
        postgresql_where="is_deleted = false",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pricing_profiles_product_active",
        table_name="pricing_product_pricing_profiles",
        postgresql_where="is_deleted = false",
    )
    op.drop_index(
        op.f("ix_pricing_product_pricing_profiles_context_id"),
        table_name="pricing_product_pricing_profiles",
    )
    op.drop_table("pricing_product_pricing_profiles")
    # ### end Alembic commands ###
