"""supplier_replace_region_with_country_and_subdivision

Revision ID: 288487847955
Revises:
Create Date: 2026-04-10 12:23:34.578042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "288487847955"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add country_code with a temporary server default so existing rows survive.
    op.add_column(
        "suppliers",
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            server_default="XX",
            comment="ISO 3166-1 alpha-2 country code",
        ),
    )
    op.alter_column("suppliers", "country_code", server_default=None)
    op.add_column(
        "suppliers",
        sa.Column(
            "subdivision_code",
            sa.String(length=10),
            nullable=True,
            comment="ISO 3166-2 subdivision code (optional)",
        ),
    )
    op.create_index(
        "ix_suppliers_country_code", "suppliers", ["country_code"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_suppliers_country_code_countries"),
        "suppliers",
        "countries",
        ["country_code"],
        ["alpha2"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_suppliers_subdivision_code_subdivisions"),
        "suppliers",
        "subdivisions",
        ["subdivision_code"],
        ["code"],
        ondelete="SET NULL",
    )
    op.drop_column("suppliers", "region")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "suppliers",
        sa.Column("region", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_suppliers_subdivision_code_subdivisions"),
        "suppliers",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_suppliers_country_code_countries"), "suppliers", type_="foreignkey"
    )
    op.drop_index("ix_suppliers_country_code", table_name="suppliers")
    op.drop_column("suppliers", "subdivision_code")
    op.drop_column("suppliers", "country_code")
    # ### end Alembic commands ###
