"""add district and district type tables

Revision ID: 2029861000f7
Revises: 289970c60fc2
Create Date: 2026-04-13 03:18:57.790281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2029861000f7"
down_revision: Union[str, Sequence[str], None] = "289970c60fc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "district_types",
        sa.Column(
            "code",
            sa.String(length=60),
            nullable=False,
            comment="Type token (e.g. RU_MUNICIPAL_DISTRICT, RU_URBAN_OKRUG)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in type filters",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_district_types")),
    )
    op.create_table(
        "district_type_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "type_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> district_types.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Translated label (e.g. Муниципальный район, Municipal district)",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_district_type_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["district_types.code"],
            name=op.f("fk_district_type_translations_type_code_district_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_type_translations")),
        sa.UniqueConstraint("type_code", "lang_code", name="uq_district_type_lang"),
    )
    op.create_index(
        "ix_district_type_tr_lang",
        "district_type_translations",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "districts",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Surrogate primary key (UUID v4)"
        ),
        sa.Column(
            "subdivision_code",
            sa.String(length=10),
            nullable=False,
            comment="FK -> subdivisions.code (parent ISO 3166-2 subdivision)",
        ),
        sa.Column(
            "type_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> district_types.code",
        ),
        sa.Column(
            "oktmo_prefix",
            sa.String(length=5),
            nullable=True,
            comment="ОКТМО level-2 prefix (5 digits: subject[2] + type[1] + ordinal[2])",
        ),
        sa.Column(
            "fias_guid",
            sa.UUID(),
            nullable=True,
            comment="ФИАС/ГАР OBJECTGUID for this municipal formation",
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid latitude (WGS 84)",
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid longitude (WGS 84)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order within parent subdivision",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Soft-delete / visibility flag",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["subdivision_code"],
            ["subdivisions.code"],
            name=op.f("fk_districts_subdivision_code_subdivisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["district_types.code"],
            name=op.f("fk_districts_type_code_district_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
        sa.UniqueConstraint("fias_guid", name=op.f("uq_districts_fias_guid")),
        sa.UniqueConstraint("oktmo_prefix", name=op.f("uq_districts_oktmo_prefix")),
    )
    op.create_index(
        "ix_districts_fias",
        "districts",
        ["fias_guid"],
        unique=False,
        postgresql_where="fias_guid IS NOT NULL",
    )
    op.create_index(
        "ix_districts_oktmo",
        "districts",
        ["oktmo_prefix"],
        unique=False,
        postgresql_where="oktmo_prefix IS NOT NULL",
    )
    op.create_index(
        "ix_districts_subdivision", "districts", ["subdivision_code"], unique=False
    )
    op.create_index(
        "ix_districts_type",
        "districts",
        ["subdivision_code", "type_code"],
        unique=False,
    )
    op.create_table(
        "district_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "district_id", sa.UUID(), nullable=False, comment="FK -> districts.id"
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Translated name (e.g. Екатеринбург, Yekaterinburg)",
        ),
        sa.Column(
            "official_name",
            sa.String(length=255),
            nullable=True,
            comment="Full official name if different from short",
        ),
        sa.Column(
            "local_variant",
            sa.String(length=255),
            nullable=True,
            comment="Alternative / local name",
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
            name=op.f("fk_district_translations_district_id_districts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_district_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_translations")),
        sa.UniqueConstraint("district_id", "lang_code", name="uq_district_lang"),
    )
    op.create_index(
        "ix_district_tr_lang", "district_translations", ["lang_code"], unique=False
    )
    op.create_index(
        "ix_district_tr_name", "district_translations", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_district_tr_name", table_name="district_translations")
    op.drop_index("ix_district_tr_lang", table_name="district_translations")
    op.drop_table("district_translations")
    op.drop_index("ix_districts_type", table_name="districts")
    op.drop_index("ix_districts_subdivision", table_name="districts")
    op.drop_index(
        "ix_districts_oktmo",
        table_name="districts",
        postgresql_where="oktmo_prefix IS NOT NULL",
    )
    op.drop_index(
        "ix_districts_fias",
        table_name="districts",
        postgresql_where="fias_guid IS NOT NULL",
    )
    op.drop_table("districts")
    op.drop_index("ix_district_type_tr_lang", table_name="district_type_translations")
    op.drop_table("district_type_translations")
    op.drop_table("district_types")
    # ### end Alembic commands ###
