"""add logistics module tables

Revision ID: 8a1e719de582
Revises: 2029861000f7
Create Date: 2026-04-13 18:49:58.266940

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a1e719de582"
down_revision: str | Sequence[str] | None = "2029861000f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_quotes",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Quote identifier (returned to client)",
        ),
        sa.Column(
            "provider_code",
            sa.String(length=50),
            nullable=False,
            comment="Logistics provider identifier",
        ),
        sa.Column(
            "service_code",
            sa.String(length=100),
            nullable=False,
            comment="Provider-specific tariff/service code",
        ),
        sa.Column(
            "service_name",
            sa.String(length=500),
            nullable=False,
            comment="Human-readable tariff name",
        ),
        sa.Column(
            "delivery_type",
            sa.Enum(
                "COURIER",
                "PICKUP_POINT",
                "POST_OFFICE",
                name="delivery_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Courier, pickup point, or post office",
        ),
        sa.Column(
            "total_cost_amount",
            sa.Integer(),
            nullable=False,
            comment="Total cost in smallest currency unit",
        ),
        sa.Column(
            "total_cost_currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "base_cost_amount",
            sa.Integer(),
            nullable=False,
            comment="Base cost in smallest currency unit",
        ),
        sa.Column(
            "base_cost_currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "insurance_cost_amount",
            sa.Integer(),
            nullable=True,
            comment="Insurance cost",
        ),
        sa.Column(
            "insurance_cost_currency",
            sa.String(length=3),
            nullable=True,
            comment="Insurance currency",
        ),
        sa.Column(
            "delivery_days_min",
            sa.Integer(),
            nullable=True,
            comment="Minimum delivery days",
        ),
        sa.Column(
            "delivery_days_max",
            sa.Integer(),
            nullable=True,
            comment="Maximum delivery days",
        ),
        sa.Column(
            "provider_payload",
            sa.Text(),
            nullable=False,
            comment="JSON-serialised opaque provider data",
        ),
        sa.Column(
            "quoted_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="When quote was generated",
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When quote expires (e.g. Yandex 10-min offer timeout)",
        ),
        sa.Column(
            "origin_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Origin address snapshot",
        ),
        sa.Column(
            "destination_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Destination address snapshot",
        ),
        sa.Column(
            "parcels_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Parcels snapshot",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_quotes")),
        comment="Server-side delivery quotes for price integrity",
    )
    op.create_index(
        "ix_delivery_quotes_expires_at", "delivery_quotes", ["expires_at"], unique=False
    )
    op.create_table(
        "provider_accounts",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key"),
        sa.Column(
            "provider_code",
            sa.String(length=50),
            nullable=False,
            comment="Logistics provider identifier (open string)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable account name",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether this account is active",
        ),
        sa.Column(
            "credentials_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Encrypted credentials (JSON)",
        ),
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific configuration",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_accounts")),
        comment="Provider account credentials and configuration",
    )
    op.create_index(
        "ix_provider_accounts_code",
        "provider_accounts",
        ["provider_code"],
        unique=False,
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key"),
        sa.Column(
            "order_id",
            sa.UUID(),
            nullable=True,
            comment="Link to order/checkout that triggered this shipment",
        ),
        sa.Column(
            "provider_code",
            sa.String(length=50),
            nullable=False,
            comment="Logistics provider identifier (open string, e.g. 'cdek')",
        ),
        sa.Column(
            "service_code",
            sa.String(length=100),
            nullable=False,
            comment="Provider-specific tariff/service code",
        ),
        sa.Column(
            "delivery_type",
            sa.Enum(
                "COURIER",
                "PICKUP_POINT",
                "POST_OFFICE",
                name="delivery_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Courier, pickup point, or post office",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "BOOKING_PENDING",
                "BOOKED",
                "CANCEL_PENDING",
                "CANCELLED",
                "FAILED",
                name="shipment_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Local integration lifecycle status",
        ),
        sa.Column(
            "origin_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Sender address as JSON",
        ),
        sa.Column(
            "destination_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Recipient address as JSON",
        ),
        sa.Column(
            "recipient_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Recipient contact info as JSON",
        ),
        sa.Column(
            "sender_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Sender contact info as JSON",
        ),
        sa.Column(
            "parcels_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="List of parcels as JSON",
        ),
        sa.Column(
            "quoted_cost_amount",
            sa.Integer(),
            nullable=False,
            comment="Quoted cost in smallest currency unit",
        ),
        sa.Column(
            "quoted_cost_currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "cod_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Cash-on-delivery config as JSON",
        ),
        sa.Column(
            "provider_shipment_id",
            sa.String(length=255),
            nullable=True,
            comment="Provider's shipment/order ID",
        ),
        sa.Column(
            "tracking_number",
            sa.String(length=255),
            nullable=True,
            comment="Provider's tracking number",
        ),
        sa.Column(
            "provider_payload",
            sa.Text(),
            nullable=True,
            comment="Opaque provider data (JSON) from quote",
        ),
        sa.Column(
            "latest_tracking_status",
            sa.Enum(
                "CREATED",
                "ACCEPTED",
                "IN_TRANSIT",
                "OUT_FOR_DELIVERY",
                "READY_FOR_PICKUP",
                "DELIVERED",
                "RETURNED",
                "LOST",
                "EXCEPTION",
                "ATTEMPT_FAILED",
                "CUSTOMS",
                name="tracking_status_enum",
                metadata=MetaData(),
            ),
            nullable=True,
            comment="Latest carrier tracking status",
        ),
        sa.Column(
            "failure_reason",
            sa.Text(),
            nullable=True,
            comment="Reason for booking/cancellation failure",
        ),
        sa.Column(
            "estimated_delivery_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Estimated delivery window as JSON",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation time",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification time",
        ),
        sa.Column(
            "booked_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When provider confirmed booking",
        ),
        sa.Column(
            "cancelled_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When cancellation was confirmed",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            comment="Optimistic locking counter",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        comment="Shipment lifecycle tracking for logistics integrations",
    )
    op.create_index("ix_shipments_order_id", "shipments", ["order_id"], unique=False)
    op.create_index(
        "ix_shipments_provider_shipment",
        "shipments",
        ["provider_code", "provider_shipment_id"],
        unique=True,
        postgresql_where="provider_shipment_id IS NOT NULL",
    )
    op.create_index("ix_shipments_status", "shipments", ["status"], unique=False)
    op.create_index(
        "ix_shipments_tracking_number", "shipments", ["tracking_number"], unique=False
    )
    op.create_table(
        "shipment_tracking_events",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key"),
        sa.Column("shipment_id", sa.UUID(), nullable=False, comment="Parent shipment"),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "ACCEPTED",
                "IN_TRANSIT",
                "OUT_FOR_DELIVERY",
                "READY_FOR_PICKUP",
                "DELIVERED",
                "RETURNED",
                "LOST",
                "EXCEPTION",
                "ATTEMPT_FAILED",
                "CUSTOMS",
                name="tracking_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Unified tracking status",
        ),
        sa.Column(
            "provider_status_code",
            sa.String(length=100),
            nullable=False,
            comment="Original provider status code",
        ),
        sa.Column(
            "provider_status_name",
            sa.String(length=500),
            nullable=False,
            comment="Original provider status description",
        ),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="When this event occurred at the carrier",
        ),
        sa.Column(
            "location",
            sa.String(length=500),
            nullable=True,
            comment="Location where the event occurred",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Additional event details"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was ingested",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_tracking_events_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_tracking_events")),
        comment="Carrier tracking event history (append-only)",
    )
    op.create_index(
        "ix_tracking_events_shipment_id",
        "shipment_tracking_events",
        ["shipment_id"],
        unique=False,
    )
    op.create_index(
        "ix_tracking_events_timestamp",
        "shipment_tracking_events",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tracking_events_timestamp", table_name="shipment_tracking_events")
    op.drop_index(
        "ix_tracking_events_shipment_id", table_name="shipment_tracking_events"
    )
    op.drop_table("shipment_tracking_events")
    op.drop_index("ix_shipments_tracking_number", table_name="shipments")
    op.drop_index("ix_shipments_status", table_name="shipments")
    op.drop_index(
        "ix_shipments_provider_shipment",
        table_name="shipments",
        postgresql_where="provider_shipment_id IS NOT NULL",
    )
    op.drop_index("ix_shipments_order_id", table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_provider_accounts_code", table_name="provider_accounts")
    op.drop_table("provider_accounts")
    op.drop_index("ix_delivery_quotes_expires_at", table_name="delivery_quotes")
    op.drop_table("delivery_quotes")
    # ### end Alembic commands ###
