"""add photo_url to customers

Revision ID: 4981af74792a
Revises: c81c05190cd9
Create Date: 2026-04-13 20:27:18.278942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4981af74792a"
down_revision: str | Sequence[str] | None = "c81c05190cd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_brands_name_lower"),
        table_name="brands",
        postgresql_ops={"lower(name::text)": "text_pattern_ops"},
    )
    op.drop_index(
        op.f("ix_categories_name_en_lower"),
        table_name="categories",
        postgresql_ops={"lower(name_i18n ->> 'en'::text)": "text_pattern_ops"},
    )
    op.drop_index(
        op.f("ix_categories_name_ru_lower"),
        table_name="categories",
        postgresql_ops={"lower(name_i18n ->> 'ru'::text)": "text_pattern_ops"},
    )
    op.add_column(
        "customers", sa.Column("photo_url", sa.String(length=512), nullable=True)
    )
    op.drop_index(
        op.f("ix_products_fts"),
        table_name="products",
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_index(
        op.f("ix_products_title_en_lower"),
        table_name="products",
        postgresql_ops={"lower(title_i18n ->> 'en'::text)": "text_pattern_ops"},
        postgresql_where="((deleted_at IS NULL) AND (status = 'PUBLISHED'::product_status_enum) AND (is_visible = true))",
    )
    op.drop_index(
        op.f("ix_products_title_ru_lower"),
        table_name="products",
        postgresql_ops={"lower(title_i18n ->> 'ru'::text)": "text_pattern_ops"},
        postgresql_where="((deleted_at IS NULL) AND (status = 'PUBLISHED'::product_status_enum) AND (is_visible = true))",
    )
    op.create_unique_constraint(
        "uq_tracking_events_shipment_ts_status",
        "shipment_tracking_events",
        ["shipment_id", "timestamp", "status"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_tracking_events_shipment_ts_status",
        "shipment_tracking_events",
        type_="unique",
    )
    op.create_index(
        op.f("ix_products_title_ru_lower"),
        "products",
        [sa.literal_column("lower(title_i18n ->> 'ru'::text)")],
        unique=False,
        postgresql_ops={"lower(title_i18n ->> 'ru'::text)": "text_pattern_ops"},
        postgresql_where="((deleted_at IS NULL) AND (status = 'PUBLISHED'::product_status_enum) AND (is_visible = true))",
    )
    op.create_index(
        op.f("ix_products_title_en_lower"),
        "products",
        [sa.literal_column("lower(title_i18n ->> 'en'::text)")],
        unique=False,
        postgresql_ops={"lower(title_i18n ->> 'en'::text)": "text_pattern_ops"},
        postgresql_where="((deleted_at IS NULL) AND (status = 'PUBLISHED'::product_status_enum) AND (is_visible = true))",
    )
    op.create_index(
        op.f("ix_products_fts"),
        "products",
        [
            sa.literal_column(
                "catalog_product_search_vector(title_i18n, description_i18n, tags::text[])"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_column("customers", "photo_url")
    op.create_index(
        op.f("ix_categories_name_ru_lower"),
        "categories",
        [sa.literal_column("lower(name_i18n ->> 'ru'::text)")],
        unique=False,
        postgresql_ops={"lower(name_i18n ->> 'ru'::text)": "text_pattern_ops"},
    )
    op.create_index(
        op.f("ix_categories_name_en_lower"),
        "categories",
        [sa.literal_column("lower(name_i18n ->> 'en'::text)")],
        unique=False,
        postgresql_ops={"lower(name_i18n ->> 'en'::text)": "text_pattern_ops"},
    )
    op.create_index(
        op.f("ix_brands_name_lower"),
        "brands",
        [sa.literal_column("lower(name::text)")],
        unique=False,
        postgresql_ops={"lower(name::text)": "text_pattern_ops"},
    )
    # ### end Alembic commands ###
