"""add_pricing_context_global_values

Revision ID: 36a91fa612cd
Revises: a5f47c19d3b2
Create Date: 2026-04-20 15:29:36.516596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36a91fa612cd"
down_revision: Union[str, Sequence[str], None] = "a5f47c19d3b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pricing_contexts",
        sa.Column(
            "global_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pricing_contexts", "global_values")
    # ### end Alembic commands ###
