"""add_pricing_supplier_type_context_mapping

Revision ID: bbb88f046c3c
Revises: 93f3549db2f1
Create Date: 2026-04-20 12:55:53.537196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "bbb88f046c3c"
down_revision: Union[str, Sequence[str], None] = "93f3549db2f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_supplier_type_context_mapping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supplier_type", sa.String(length=64), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f(
                "ck_pricing_supplier_type_context_mapping_ck_pricing_supplier_type_context_mapping_version_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_pricing_supplier_type_context_mapping")
        ),
        sa.UniqueConstraint(
            "supplier_type", name="uq_pricing_supplier_type_context_mapping_type"
        ),
        comment="SupplierType → default pricing context (FRD §SupplierType→Context Mapping)",
    )
    op.create_index(
        op.f("ix_pricing_supplier_type_context_mapping_context_id"),
        "pricing_supplier_type_context_mapping",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_supplier_type_context_mapping_supplier_type"),
        "pricing_supplier_type_context_mapping",
        ["supplier_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pricing_supplier_type_context_mapping_supplier_type"),
        table_name="pricing_supplier_type_context_mapping",
    )
    op.drop_index(
        op.f("ix_pricing_supplier_type_context_mapping_context_id"),
        table_name="pricing_supplier_type_context_mapping",
    )
    op.drop_table("pricing_supplier_type_context_mapping")
    # ### end Alembic commands ###
