"""add_pricing_category_settings

Revision ID: 93f3549db2f1
Revises: 07cd330ed345
Create Date: 2026-04-20 12:38:08.463632

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93f3549db2f1"
down_revision: str | Sequence[str] | None = "07cd330ed345"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_category_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column(
            "values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "ranges",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "explicit_no_ranges", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("version_lock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_lock >= 0",
            name=op.f(
                "ck_pricing_category_settings_ck_pricing_category_settings_version_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_category_settings")),
        sa.UniqueConstraint(
            "category_id", "context_id", name="uq_pricing_category_settings_cat_ctx"
        ),
        comment="Per-(category, context) pricing overrides (FRD §Category Pricing Settings)",
    )
    op.create_index(
        op.f("ix_pricing_category_settings_category_id"),
        "pricing_category_settings",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_category_settings_context_id"),
        "pricing_category_settings",
        ["context_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pricing_category_settings_context_id"),
        table_name="pricing_category_settings",
    )
    op.drop_index(
        op.f("ix_pricing_category_settings_category_id"),
        table_name="pricing_category_settings",
    )
    op.drop_table("pricing_category_settings")
    # ### end Alembic commands ###
