"""fix_media_main_index_case

Revision ID: 3c5e991dde6c
Revises: 43de4d0e8914
Create Date: 2026-03-22 19:25:20.475884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "3c5e991dde6c"
down_revision: Union[str, Sequence[str], None] = "43de4d0e8914"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
