"""user_profiles

Revision ID: ccb23627d9ae
Revises: dc46be56f9c7
Create Date: 2026-03-22 15:06:42.879074

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccb23627d9ae"
down_revision: str | Sequence[str] | None = "dc46be56f9c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_email", sa.String(length=320), nullable=True),
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("referral_code", sa.String(length=12), nullable=True),
        sa.Column("referred_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["identities.id"],
            name=op.f("fk_customers_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["customers.id"],
            name=op.f("fk_customers_referred_by_customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("referral_code", name=op.f("uq_customers_referral_code")),
        comment="Customer profiles with referral data (GDPR-isolated)",
    )
    op.create_table(
        "staff_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column("profile_email", sa.String(length=320), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["identities.id"],
            name=op.f("fk_staff_members_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["identities.id"],
            name=op.f("fk_staff_members_invited_by_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_members")),
        comment="Staff member profiles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff_members")
    op.drop_table("customers")
    # ### end Alembic commands ###
