"""geo_reference_data

Revision ID: e3f0af08a664
Revises: ccb23627d9ae
Create Date: 2026-03-22 15:07:04.833791

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3f0af08a664"
down_revision: str | Sequence[str] | None = "ccb23627d9ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column(
            "alpha2",
            sa.String(length=2),
            nullable=False,
            comment="ISO 3166-1 Alpha-2 code (e.g. KZ)",
        ),
        sa.Column(
            "alpha3",
            sa.String(length=3),
            nullable=False,
            comment="ISO 3166-1 Alpha-3 code (e.g. KAZ)",
        ),
        sa.Column(
            "numeric",
            sa.String(length=3),
            nullable=False,
            comment="ISO 3166-1 Numeric code, zero-padded (e.g. 398)",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("alpha2", name=op.f("pk_countries")),
        sa.UniqueConstraint("alpha3", name=op.f("uq_countries_alpha3")),
        sa.UniqueConstraint("numeric", name=op.f("uq_countries_numeric")),
    )
    op.create_table(
        "currencies",
        sa.Column(
            "code",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 alpha-3 code (e.g. UZS, USD, EUR)",
        ),
        sa.Column(
            "numeric",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 numeric code, zero-padded (e.g. 840, 978)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Common English name (e.g. US Dollar)",
        ),
        sa.Column(
            "minor_unit",
            sa.SmallInteger(),
            nullable=True,
            comment="Decimal places (2 for USD, 0 for JPY, 3 for BHD, NULL for XXX)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Available for selection in UI / API",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in currency pickers",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
        sa.UniqueConstraint("numeric", name=op.f("uq_currencies_numeric")),
    )
    op.create_index("ix_currencies_active", "currencies", ["is_active"], unique=False)
    op.create_index("ix_currencies_name", "currencies", ["name"], unique=False)
    op.create_index("ix_currencies_numeric", "currencies", ["numeric"], unique=False)
    op.create_table(
        "languages",
        sa.Column(
            "code",
            sa.String(length=12),
            nullable=False,
            comment="IETF BCP 47 tag (e.g. uz-Latn, en, ru)",
        ),
        sa.Column(
            "iso639_1",
            sa.String(length=2),
            nullable=True,
            comment="ISO 639-1 alpha-2 (e.g. uz, ru, en)",
        ),
        sa.Column(
            "iso639_2",
            sa.String(length=3),
            nullable=True,
            comment="ISO 639-2/T alpha-3 (e.g. uzb, rus, eng)",
        ),
        sa.Column(
            "iso639_3",
            sa.String(length=3),
            nullable=True,
            comment="ISO 639-3 alpha-3 (e.g. uzb, kaa)",
        ),
        sa.Column(
            "script",
            sa.String(length=4),
            nullable=True,
            comment="ISO 15924 script code (e.g. Latn, Cyrl, Arab)",
        ),
        sa.Column(
            "name_en",
            sa.String(length=100),
            nullable=False,
            comment="English name (e.g. Uzbek (Latin))",
        ),
        sa.Column(
            "name_native",
            sa.String(length=100),
            nullable=False,
            comment="Endonym (e.g. Русский)",
        ),
        sa.Column(
            "direction",
            sa.String(length=3),
            server_default="ltr",
            nullable=False,
            comment="Text direction: ltr or rtl",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Available for selection in UI",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Default fallback language (exactly one True)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in language pickers",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_languages")),
    )
    op.create_index("ix_languages_active", "languages", ["is_active"], unique=False)
    op.create_index("ix_languages_iso639_1", "languages", ["iso639_1"], unique=False)
    op.create_table(
        "subdivision_categories",
        sa.Column(
            "code",
            sa.String(length=60),
            nullable=False,
            comment="ISO category token (e.g. PROVINCE, EMIRATE)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order in category filters",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_subdivision_categories")),
    )
    op.create_table(
        "country_currencies",
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2 (ISO 3166-1)",
        ),
        sa.Column(
            "currency_code",
            sa.String(length=3),
            nullable=False,
            comment="FK -> currencies.code (ISO 4217)",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether this is the country's primary/official currency",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_country_currencies_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_country_currencies_currency_code_currencies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "country_code", "currency_code", name=op.f("pk_country_currencies")
        ),
    )
    op.create_index(
        "ix_country_currencies_currency_code",
        "country_currencies",
        ["currency_code"],
        unique=False,
    )
    op.create_table(
        "country_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Translated short name (e.g. Россия)",
        ),
        sa.Column(
            "official_name",
            sa.String(length=255),
            nullable=True,
            comment="Official name if different from short",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_country_translations_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_country_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_translations")),
        sa.UniqueConstraint("country_code", "lang_code", name="uq_country_lang"),
    )
    op.create_index("ix_country_tr_lang", "country_translations", ["lang_code"], unique=False)
    op.create_index("ix_country_tr_name", "country_translations", ["name"], unique=False)
    op.create_table(
        "currency_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "currency_code",
            sa.String(length=3),
            nullable=False,
            comment="FK -> currencies.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Translated currency name (e.g. Доллар США)",
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_currency_translations_currency_code_currencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_currency_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency_translations")),
        sa.UniqueConstraint("currency_code", "lang_code", name="uq_currency_lang"),
    )
    op.create_index("ix_currency_tr_lang", "currency_translations", ["lang_code"], unique=False)
    op.create_index("ix_currency_tr_name", "currency_translations", ["name"], unique=False)
    op.create_table(
        "subdivision_category_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "category_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> subdivision_categories.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Translated label (e.g. Область, Province)",
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["subdivision_categories.code"],
            name=op.f("fk_subdivision_category_translations_category_code_subdivision_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_subdivision_category_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subdivision_category_translations")),
        sa.UniqueConstraint("category_code", "lang_code", name="uq_sub_category_lang"),
    )
    op.create_index(
        "ix_sub_cat_tr_lang",
        "subdivision_category_translations",
        ["lang_code"],
        unique=False,
    )
    op.create_table(
        "subdivisions",
        sa.Column(
            "code",
            sa.String(length=10),
            nullable=False,
            comment="ISO 3166-2 code (e.g. RU-MOW, UZ-TO)",
        ),
        sa.Column(
            "country_code",
            sa.String(length=2),
            nullable=False,
            comment="FK -> countries.alpha2",
        ),
        sa.Column(
            "category_code",
            sa.String(length=60),
            nullable=False,
            comment="FK -> subdivision_categories.code",
        ),
        sa.Column(
            "parent_code",
            sa.String(length=10),
            nullable=True,
            comment="Parent subdivision for nested levels",
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid latitude (WGS 84)",
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=10, scale=7),
            nullable=True,
            comment="Centroid longitude (WGS 84)",
        ),
        sa.Column(
            "sort_order",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
            comment="Display order within parent country",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Soft-delete / visibility flag",
        ),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["subdivision_categories.code"],
            name=op.f("fk_subdivisions_category_code_subdivision_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
            name=op.f("fk_subdivisions_country_code_countries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_code"],
            ["subdivisions.code"],
            name=op.f("fk_subdivisions_parent_code_subdivisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_subdivisions")),
    )
    op.create_index(
        "ix_subdivisions_category",
        "subdivisions",
        ["country_code", "category_code"],
        unique=False,
    )
    op.create_index("ix_subdivisions_country", "subdivisions", ["country_code"], unique=False)
    op.create_index("ix_subdivisions_parent", "subdivisions", ["parent_code"], unique=False)
    op.create_table(
        "subdivision_translations",
        sa.Column("id", sa.UUID(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "subdivision_code",
            sa.String(length=10),
            nullable=False,
            comment="FK -> subdivisions.code",
        ),
        sa.Column(
            "lang_code",
            sa.String(length=12),
            nullable=False,
            comment="FK -> languages.code (IETF BCP 47)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Translated name (e.g. Москва, Moscow)",
        ),
        sa.Column(
            "official_name",
            sa.String(length=255),
            nullable=True,
            comment="Full official name if different from short",
        ),
        sa.Column(
            "local_variant",
            sa.String(length=255),
            nullable=True,
            comment="Alternative / local name (e.g. Yugra for KhMAO)",
        ),
        sa.ForeignKeyConstraint(
            ["lang_code"],
            ["languages.code"],
            name=op.f("fk_subdivision_translations_lang_code_languages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subdivision_code"],
            ["subdivisions.code"],
            name=op.f("fk_subdivision_translations_subdivision_code_subdivisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subdivision_translations")),
        sa.UniqueConstraint("subdivision_code", "lang_code", name="uq_subdivision_lang"),
    )
    op.create_index("ix_sub_tr_lang", "subdivision_translations", ["lang_code"], unique=False)
    op.create_index("ix_sub_tr_name", "subdivision_translations", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sub_tr_name", table_name="subdivision_translations")
    op.drop_index("ix_sub_tr_lang", table_name="subdivision_translations")
    op.drop_table("subdivision_translations")
    op.drop_index("ix_subdivisions_parent", table_name="subdivisions")
    op.drop_index("ix_subdivisions_country", table_name="subdivisions")
    op.drop_index("ix_subdivisions_category", table_name="subdivisions")
    op.drop_table("subdivisions")
    op.drop_index("ix_sub_cat_tr_lang", table_name="subdivision_category_translations")
    op.drop_table("subdivision_category_translations")
    op.drop_index("ix_currency_tr_name", table_name="currency_translations")
    op.drop_index("ix_currency_tr_lang", table_name="currency_translations")
    op.drop_table("currency_translations")
    op.drop_index("ix_country_tr_name", table_name="country_translations")
    op.drop_index("ix_country_tr_lang", table_name="country_translations")
    op.drop_table("country_translations")
    op.drop_index("ix_country_currencies_currency_code", table_name="country_currencies")
    op.drop_table("country_currencies")
    op.drop_table("subdivision_categories")
    op.drop_index("ix_languages_iso639_1", table_name="languages")
    op.drop_index("ix_languages_active", table_name="languages")
    op.drop_table("languages")
    op.drop_index("ix_currencies_numeric", table_name="currencies")
    op.drop_index("ix_currencies_name", table_name="currencies")
    op.drop_index("ix_currencies_active", table_name="currencies")
    op.drop_table("currencies")
    op.drop_table("countries")
    # ### end Alembic commands ###
