"""add_media_processing_columns

Revision ID: 43de4d0e8914
Revises: dcb663d40ddd
Create Date: 2026-03-22 18:55:03.202755

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43de4d0e8914"
down_revision: str | Sequence[str] | None = "dcb663d40ddd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_assets",
        sa.Column(
            "processing_status",
            sa.String(length=30),
            nullable=True,
            comment="FSM: PENDING_UPLOAD, PROCESSING, COMPLETED, FAILED",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "raw_object_key",
            sa.String(length=1024),
            nullable=True,
            comment="S3 key for raw upload (before AI processing)",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "public_url",
            sa.String(length=1024),
            nullable=True,
            comment="Final public URL after processing",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_assets", "public_url")
    op.drop_column("media_assets", "raw_object_key")
    op.drop_column("media_assets", "processing_status")
    # ### end Alembic commands ###
