"""infrastructure_outbox_and_dlq

Revision ID: 7d51a5971b94
Revises:
Create Date: 2026-03-22 15:06:04.310576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d51a5971b94"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_tasks",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key"),
        sa.Column(
            "task_name",
            sa.String(length=255),
            nullable=False,
            comment="TaskIQ task name",
        ),
        sa.Column(
            "task_id",
            sa.String(length=255),
            nullable=False,
            comment="TaskIQ message ID",
        ),
        sa.Column(
            "args",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Task arguments",
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Task labels (correlation_id, etc.)",
        ),
        sa.Column("error_message", sa.Text(), nullable=False, comment="Error message text"),
        sa.Column(
            "retry_count",
            sa.Integer(),
            nullable=False,
            comment="Number of retry attempts executed",
        ),
        sa.Column(
            "failed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the final failure",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failed_tasks")),
    )
    op.create_table(
        "outbox_messages",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key (UUIDv7 for time-based sorting)",
        ),
        sa.Column(
            "aggregate_type",
            sa.String(length=255),
            nullable=False,
            comment="Source aggregate type (Brand, Order, ...)",
        ),
        sa.Column(
            "aggregate_id",
            sa.String(length=255),
            nullable=False,
            comment="Source aggregate ID",
        ),
        sa.Column(
            "event_type",
            sa.String(length=255),
            nullable=False,
            comment="Domain event name (BrandLogoConfirmedEvent, ...)",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Serialized event body",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the event was written to the outbox",
        ),
        sa.Column(
            "processed_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp of successful broker publication (NULL = pending)",
        ),
        sa.Column(
            "correlation_id",
            sa.String(length=64),
            nullable=True,
            comment="Trace correlation ID (HTTP request_id -> Outbox -> TaskIQ)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        "ix_outbox_processed_created",
        "outbox_messages",
        ["processed_at", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_processed_created", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_table("failed_tasks")
    # ### end Alembic commands ###
