"""add_processed_object_key

Revision ID: a1b2c3d4e5f6
Revises: 7406c4bd5771
Create Date: 2026-03-23 02:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "7406c4bd5771"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_assets",
        sa.Column(
            "processed_object_key",
            sa.String(length=1024),
            nullable=True,
            comment="S3 key for processed file (set on complete_processing)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_assets", "processed_object_key")
    # ### end Alembic commands ###
