"""add attribute families replace category bindings

Revision ID: 419e4b0bb222
Revises: 9e956151d5ad
Create Date: 2026-03-25 02:43:01.343764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "419e4b0bb222"
down_revision: str | Sequence[str] | None = "9e956151d5ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_families",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["attribute_families.id"],
            name=op.f("fk_attribute_families_parent_id_attribute_families"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_families")),
        sa.UniqueConstraint("code", name=op.f("uq_attribute_families_code")),
    )
    op.create_index(
        "ix_attribute_families_level_sort",
        "attribute_families",
        ["level", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_families_parent_id"),
        "attribute_families",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "family_attribute_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "requirement_level",
            sa.Enum(
                "REQUIRED",
                "RECOMMENDED",
                "OPTIONAL",
                name="requirement_level_enum",
                metadata=MetaData(),
            ),
            server_default=sa.text("'optional'"),
            nullable=False,
        ),
        sa.Column(
            "flag_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "filter_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_family_attribute_bindings_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["attribute_families.id"],
            name=op.f("fk_family_attribute_bindings_family_id_attribute_families"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_attribute_bindings")),
        sa.UniqueConstraint(
            "family_id", "attribute_id", name="uix_family_attr_binding"
        ),
    )
    op.create_index(
        op.f("ix_family_attribute_bindings_attribute_id"),
        "family_attribute_bindings",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_attribute_bindings_family_id"),
        "family_attribute_bindings",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "family_attribute_exclusions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_family_attribute_exclusions_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["attribute_families.id"],
            name=op.f("fk_family_attribute_exclusions_family_id_attribute_families"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_attribute_exclusions")),
        sa.UniqueConstraint(
            "family_id", "attribute_id", name="uix_family_attr_exclusion"
        ),
    )
    op.create_index(
        op.f("ix_family_attribute_exclusions_attribute_id"),
        "family_attribute_exclusions",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_attribute_exclusions_family_id"),
        "family_attribute_exclusions",
        ["family_id"],
        unique=False,
    )
    op.add_column("categories", sa.Column("family_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_categories_family_id"), "categories", ["family_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_categories_family_id_attribute_families"),
        "categories",
        "attribute_families",
        ["family_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Drop category_attribute_rules table (replaced by family_attribute_bindings)
    op.drop_index("uix_cat_attr_rule", table_name="category_attribute_rules")
    op.drop_index(
        op.f("ix_category_attribute_rules_category_id"),
        table_name="category_attribute_rules",
    )
    op.drop_index(
        op.f("ix_category_attribute_rules_attribute_id"),
        table_name="category_attribute_rules",
    )
    op.drop_table("category_attribute_rules")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_categories_family_id_attribute_families"),
        "categories",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_categories_family_id"), table_name="categories")
    op.drop_column("categories", "family_id")
    op.drop_index(
        op.f("ix_family_attribute_exclusions_family_id"),
        table_name="family_attribute_exclusions",
    )
    op.drop_index(
        op.f("ix_family_attribute_exclusions_attribute_id"),
        table_name="family_attribute_exclusions",
    )
    op.drop_table("family_attribute_exclusions")
    op.drop_index(
        op.f("ix_family_attribute_bindings_family_id"),
        table_name="family_attribute_bindings",
    )
    op.drop_index(
        op.f("ix_family_attribute_bindings_attribute_id"),
        table_name="family_attribute_bindings",
    )
    op.drop_table("family_attribute_bindings")
    op.drop_index(
        op.f("ix_attribute_families_parent_id"), table_name="attribute_families"
    )
    op.drop_index("ix_attribute_families_level_sort", table_name="attribute_families")
    op.drop_table("attribute_families")

    # Recreate category_attribute_rules table
    op.create_table(
        "category_attribute_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "requirement_level",
            sa.Enum(
                "REQUIRED",
                "RECOMMENDED",
                "OPTIONAL",
                name="requirement_level_enum",
                metadata=MetaData(),
            ),
            server_default="OPTIONAL",
            nullable=False,
        ),
        sa.Column(
            "flag_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "filter_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_category_attribute_rules_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_attribute_rules_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_attribute_rules")),
    )
    op.create_index(
        op.f("ix_category_attribute_rules_attribute_id"),
        "category_attribute_rules",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_category_attribute_rules_category_id"),
        "category_attribute_rules",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "uix_cat_attr_rule",
        "category_attribute_rules",
        ["category_id", "attribute_id"],
        unique=True,
    )
    # ### end Alembic commands ###
