"""simplify media_assets and brands drop storage_objects

Revision ID: 52b8a4dcd72a
Revises:
Create Date: 2026-03-25 18:55:19.387244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52b8a4dcd72a"
down_revision: str | Sequence[str] | None = "c3a0c360de78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_objects_bucket_name"), table_name="storage_objects")
    op.drop_index(op.f("ix_storage_objects_content_type"), table_name="storage_objects")
    op.drop_index(op.f("ix_storage_objects_owner_module"), table_name="storage_objects")
    op.drop_index(
        op.f("uix_storage_active_object"),
        table_name="storage_objects",
        postgresql_where="(is_latest = true)",
    )
    op.drop_table("storage_objects")
    op.add_column(
        "brands",
        sa.Column(
            "logo_storage_object_id",
            sa.UUID(),
            nullable=True,
            comment="Reference to storage_objects.id in ImageBackend",
        ),
    )
    op.drop_index(op.f("ix_brands_logo_file_id"), table_name="brands")
    op.create_index(
        op.f("ix_brands_logo_storage_object_id"),
        "brands",
        ["logo_storage_object_id"],
        unique=False,
    )
    op.drop_column("brands", "logo_file_id")
    op.drop_column("brands", "logo_status")
    op.add_column(
        "media_assets",
        sa.Column(
            "url",
            sa.String(length=1024),
            nullable=True,
            comment="Public URL of the media asset",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "image_variants",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Image size variants: [{size, width, height, url}, ...]",
        ),
    )
    op.drop_index(
        "uix_media_single_main_per_variant",
        table_name="media_assets",
    )
    op.create_index(
        "uix_media_single_main_per_variant",
        "media_assets",
        ["product_id", "variant_id"],
        unique=True,
        postgresql_where="role = 'MAIN'",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_column("media_assets", "url")
    op.drop_column("media_assets", "processed_object_key")
    op.drop_column("media_assets", "raw_object_key")
    op.drop_column("media_assets", "external_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_assets",
        sa.Column(
            "external_url",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=True,
            comment="Direct URL (e.g. youtube.com/...) when is_external is true",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "raw_object_key",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=True,
            comment="S3 key for raw upload (before AI processing)",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "processed_object_key",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=True,
            comment="S3 key for processed file (set on complete_processing)",
        ),
    )
    op.add_column(
        "media_assets",
        sa.Column(
            "url",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=True,
            comment="Final public URL after processing",
        ),
    )
    op.drop_column("media_assets", "image_variants")
    op.drop_column("media_assets", "url")
    op.drop_index(
        "uix_media_single_main_per_variant",
        table_name="media_assets",
    )
    op.create_index(
        "uix_media_single_main_per_variant",
        "media_assets",
        ["product_id", "variant_id"],
        unique=True,
        postgresql_where="role = 'MAIN'",
        postgresql_nulls_not_distinct=True,
    )
    op.add_column(
        "brands",
        sa.Column(
            "logo_status",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=True,
            comment="FSM: current stage of logo upload/processing",
        ),
    )
    op.add_column(
        "brands",
        sa.Column(
            "logo_file_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="Soft-link to storage_objects.id (Storage module)",
        ),
    )
    op.drop_index(op.f("ix_brands_logo_storage_object_id"), table_name="brands")
    op.create_index(
        op.f("ix_brands_logo_file_id"), "brands", ["logo_file_id"], unique=False
    )
    op.drop_column("brands", "logo_storage_object_id")
    op.create_table(
        "storage_objects",
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Internal object ID in the database",
        ),
        sa.Column(
            "bucket_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="S3 bucket name",
        ),
        sa.Column(
            "object_key",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
            comment="Full path to the file within the bucket (e.g. 'brands/123/logo.webp')",
        ),
        sa.Column(
            "version_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="S3 object version ID",
        ),
        sa.Column(
            "is_latest",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
            comment="Whether this version is the current active one",
        ),
        sa.Column(
            "size_bytes",
            sa.BIGINT(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="File size in bytes",
        ),
        sa.Column(
            "etag",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
            comment="MD5 hash returned by S3 (useful for integrity checks)",
        ),
        sa.Column(
            "content_type",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="MIME type (e.g. 'image/jpeg', 'application/pdf')",
        ),
        sa.Column(
            "content_encoding",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cache_control", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "owner_module",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Owning module name (e.g. 'catalog', 'users') for auditing",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_modified_in_s3",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Last modification timestamp on the S3 side (updated when ETag changes)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_objects")),
    )
    op.create_index(
        op.f("uix_storage_active_object"),
        "storage_objects",
        ["bucket_name", "object_key"],
        unique=True,
        postgresql_where="(is_latest = true)",
    )
    op.create_index(
        op.f("ix_storage_objects_owner_module"),
        "storage_objects",
        ["owner_module"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_objects_content_type"),
        "storage_objects",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_objects_bucket_name"),
        "storage_objects",
        ["bucket_name"],
        unique=False,
    )
    # ### end Alembic commands ###
