"""add effective_family_id to categories

Revision ID: bf774eee205e
Revises: 4daedf5c6e1e
Create Date: 2026-03-26 01:14:54.467292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "bf774eee205e"
down_revision: Union[str, Sequence[str], None] = "4daedf5c6e1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "effective_family_id",
            sa.UUID(),
            nullable=True,
            comment="Computed: own family_id or inherited from nearest ancestor",
        ),
    )
    op.create_index(
        op.f("ix_categories_effective_family_id"),
        "categories",
        ["effective_family_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_categories_effective_family_id_attribute_families"),
        "categories",
        "attribute_families",
        ["effective_family_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Backfill: copy family_id to effective_family_id for explicitly assigned categories
    op.execute(
        sa.text("""
        UPDATE categories
        SET effective_family_id = family_id
        WHERE family_id IS NOT NULL
    """)
    )

    # Propagate level 1: children that inherit from parent
    op.execute(
        sa.text("""
        UPDATE categories child
        SET effective_family_id = parent.effective_family_id
        FROM categories parent
        WHERE child.parent_id = parent.id
          AND child.family_id IS NULL
          AND parent.effective_family_id IS NOT NULL
          AND child.effective_family_id IS NULL
    """)
    )

    # Propagate level 2: grandchildren (MAX_CATEGORY_DEPTH = 3)
    op.execute(
        sa.text("""
        UPDATE categories grandchild
        SET effective_family_id = parent.effective_family_id
        FROM categories parent
        WHERE grandchild.parent_id = parent.id
          AND grandchild.family_id IS NULL
          AND parent.effective_family_id IS NOT NULL
          AND grandchild.effective_family_id IS NULL
    """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_categories_effective_family_id_attribute_families"),
        "categories",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_categories_effective_family_id"), table_name="categories")
    op.drop_column("categories", "effective_family_id")
    # ### end Alembic commands ###
