# src/modules/storage/domain/interfaces.py
import uuid
from typing import Optional, Protocol, Sequence

from src.modules.storage.domain.entities import StorageFile


class IStorageRepository(Protocol):
    """Доменный контракт для работы с хранилищем метаданных файлов."""

    async def add(self, storage_file: StorageFile) -> None: ...
    async def update(self, storage_file: StorageFile) -> None: ...
    async def get_by_key(self, key: uuid.UUID) -> Optional[StorageFile]: ...
    async def get_active_by_key(
        self, bucket_name: str, object_key: str
    ) -> Optional[StorageFile]: ...
    async def get_all_versions(
        self, bucket_name: str, object_key: str
    ) -> Sequence[StorageFile]: ...
    async def deactivate_previous_versions(
        self, bucket_name: str, object_key: str
    ) -> None: ...
    async def mark_as_deleted(self, bucket_name: str, object_key: str) -> None: ...
