export const mockPurchasedProducts = [
  {
    id: 1,
    name: "Туфли Prada Monolith Brushed Original Bla...",
    brand: "Prada",
    price: "112 490 ₽",
    image: "/products/shoes-1.png",
    isFavorite: false,
    deliveryDate: "30 марта",
  },
  {
    id: 2,
    name: "Лонгслив Comme Des Garcons Play",
    brand: "Comme Des Garcons",
    price: "12 990 ₽",
    image: "/products/t-shirt-1.png",
    isFavorite: true,
    deliveryDate: "Послезавтра",
  },
  {
    id: 3,
    name: "Футболка Daze",
    brand: "Daze",
    price: "2 890 ₽",
    image: "/products/t-shirt-2.png",
    isFavorite: false,
    deliveryDate: "30 марта",
  },
  {
    id: 4,
    name: "Кроссовки Nike Dunk Low",
    brand: "Nike",
    price: "12 990 ₽",
    image: "/products/shoes-2.png",
    isFavorite: true,
    deliveryDate: "Послезавтра",
  },
  {
    id: 5,
    name: "Куртка зимняя",
    brand: "NoName",
    price: "15 990 ₽",
    image: "/products/t-shirt-2.png",
    isFavorite: false,
    deliveryDate: "30 марта",
  },
  {
    id: 6,
    name: "Лонгслив Comme Des Garçons Play",
    brand: "Comme Des Garcons",
    price: "2 890 ₽",
    image: "/products/t-shirt-1.png",
    isFavorite: false,
    deliveryDate: "Послезавтра",
  },
];
