"""init

Revision ID: 9108a4a20a82
Revises:
Create Date: 2026-03-13 14:02:04.331723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9108a4a20a82"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attributes",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "name_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "data_type",
            sa.Enum(
                "STRING",
                "INTEGER",
                "FLOAT",
                "BOOLEAN",
                name="attribute_data_type_enum",
                metadata=MetaData(),
            ),
            server_default="STRING",
            nullable=False,
        ),
        sa.Column(
            "ui_type",
            sa.Enum(
                "TEXT_BUTTON",
                "COLOR_SWATCH",
                "DROPDOWN",
                "CHECKBOX",
                "RANGE_SLIDER",
                name="attribute_ui_type_enum",
                metadata=MetaData(),
            ),
            server_default="TEXT_BUTTON",
            nullable=False,
        ),
        sa.Column(
            "is_dictionary",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributes")),
    )
    op.create_index(
        "ix_attributes_name_i18n_gin",
        "attributes",
        ["name_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("uix_attributes_code", "attributes", ["code"], unique=True)
    op.create_index("uix_attributes_slug", "attributes", ["slug"], unique=True)
    op.create_table(
        "brands",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Первичный ключ (UUIDv7 для сортировки по времени)",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название бренда"
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-идентификатор для роутинга",
        ),
        sa.Column(
            "logo_file_id",
            sa.UUID(),
            nullable=True,
            comment="Soft-link на storage_objects.id (Модуль Storage)",
        ),
        sa.Column(
            "logo_status",
            sa.Enum(
                "PENDING_UPLOAD",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="mediaprocessingstatus",
                metadata=MetaData(),
                native_enum=False,
                length=30,
            ),
            nullable=True,
            comment="FSM: Текущий этап загрузки/обработки логотипа",
        ),
        sa.Column(
            "logo_url",
            sa.String(length=1024),
            nullable=True,
            comment="Кэш публичного URL из модуля Storage",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        comment="Справочник брендов каталога",
    )
    op.create_index(
        op.f("ix_brands_logo_file_id"), "brands", ["logo_file_id"], unique=False
    )
    op.create_index(op.f("ix_brands_slug"), "brands", ["slug"], unique=False)
    op.create_index("uix_brands_name", "brands", ["name"], unique=True)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("full_slug", sa.String(length=1000), nullable=False),
        sa.Column("level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_full_slug"), "categories", ["full_slug"], unique=False
    )
    op.create_index(
        "ix_categories_full_slug_ops",
        "categories",
        ["full_slug"],
        unique=False,
        postgresql_ops={"full_slug": "varchar_pattern_ops"},
    )
    op.create_index(op.f("ix_categories_level"), "categories", ["level"], unique=False)
    op.create_index(
        "ix_categories_level_sort", "categories", ["level", "sort_order"], unique=False
    )
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_index(
        op.f("ix_categories_sort_order"), "categories", ["sort_order"], unique=False
    )
    op.create_index(
        "uix_categories_slug",
        "categories",
        ["parent_id", "slug"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CROSS_BORDER", "LOCAL", name="supplier_type_enum", metadata=MetaData()
            ),
            nullable=False,
        ),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_table(
        "attribute_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "value_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "search_aliases",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("group_code", sa.String(length=100), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_attribute_values_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_values")),
    )
    op.create_index(
        "ix_attr_val_search_aliases_gin",
        "attribute_values",
        ["search_aliases"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_attr_val_value_i18n_gin",
        "attribute_values",
        ["value_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_attribute_values_attribute_id"),
        "attribute_values",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_values_group_code"),
        "attribute_values",
        ["group_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attribute_values_slug"), "attribute_values", ["slug"], unique=False
    )
    op.create_index(
        "uix_attr_val_code", "attribute_values", ["attribute_id", "code"], unique=True
    )
    op.create_index(
        "uix_attr_val_slug", "attribute_values", ["attribute_id", "slug"], unique=True
    )
    op.create_table(
        "category_attribute_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_category_attribute_rules_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_attribute_rules_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_attribute_rules")),
    )
    op.create_index(
        op.f("ix_category_attribute_rules_attribute_id"),
        "category_attribute_rules",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_category_attribute_rules_category_id"),
        "category_attribute_rules",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "uix_cat_attr_rule",
        "category_attribute_rules",
        ["category_id", "attribute_id"],
        unique=True,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("primary_category_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "title_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_i18n",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "popularity_score",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("country_of_origin", sa.String(length=2), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ENRICHING",
                "READY_FOR_REVIEW",
                "PUBLISHED",
                "ARCHIVED",
                name="product_status_enum",
                metadata=MetaData(),
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "is_visible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_category_id"],
            ["categories.id"],
            name=op.f("fk_products_primary_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_products_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "ix_products_attributes_gin",
        "products",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False
    )
    op.create_index(
        "ix_products_catalog_listing",
        "products",
        ["brand_id", "primary_category_id", "status", "popularity_score"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.create_index(
        op.f("ix_products_deleted_at"), "products", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_products_primary_category_id"),
        "products",
        ["primary_category_id"],
        unique=False,
    )
    op.create_index(
        "ix_products_sale_listing",
        "products",
        ["brand_id", "primary_category_id", "popularity_score"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_index(
        op.f("ix_products_supplier_id"), "products", ["supplier_id"], unique=False
    )
    op.create_index(
        "ix_products_tags_gin",
        "products",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_products_title_gin",
        "products",
        ["title_i18n"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "uix_products_slug",
        "products",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("attribute_value_id", sa.UUID(), nullable=True),
        sa.Column(
            "media_type",
            sa.Enum(
                "IMAGE",
                "VIDEO",
                "MODEL_3D",
                "DOCUMENT",
                name="media_type_enum",
                metadata=MetaData(),
            ),
            server_default="IMAGE",
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "MAIN",
                "HOVER",
                "GALLERY",
                "HERO_VIDEO",
                "SIZE_GUIDE",
                "PACKAGING",
                name="media_role_enum",
                metadata=MetaData(),
            ),
            server_default="GALLERY",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "storage_object_id",
            sa.UUID(),
            nullable=True,
            comment="Ссылка на storage_objects.id (Единый реестр файлов)",
        ),
        sa.Column(
            "is_external",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг внешнего ресурса (не управляемого нашим S3)",
        ),
        sa.Column(
            "external_url",
            sa.String(length=1024),
            nullable=True,
            comment="Прямая ссылка (например, youtube.com/...), если is_external = true",
        ),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_values.id"],
            name=op.f("fk_media_assets_attribute_value_id_attribute_values"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_media_assets_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        op.f("ix_media_assets_attribute_value_id"),
        "media_assets",
        ["attribute_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_media_type"), "media_assets", ["media_type"], unique=False
    )
    op.create_index(
        "ix_media_assets_product_attr",
        "media_assets",
        ["product_id", "attribute_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_product_id"), "media_assets", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_storage_object_id"),
        "media_assets",
        ["storage_object_id"],
        unique=False,
    )
    op.create_index(
        "uix_media_single_main_per_color",
        "media_assets",
        ["product_id", "attribute_value_id"],
        unique=True,
        postgresql_where=sa.text("role = 'MAIN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku_code", sa.String(length=100), nullable=False),
        sa.Column("variant_hash", sa.String(length=64), nullable=False),
        sa.Column("main_image_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "attributes_cache",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "price",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Базовая цена в минимальных единицах валюты",
        ),
        sa.Column(
            "compare_at_price",
            sa.Integer(),
            nullable=True,
            comment="Старая цена (для зачеркивания)",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'RUB'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_skus_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
        sa.UniqueConstraint("variant_hash", name=op.f("uq_skus_variant_hash")),
    )
    op.create_index(op.f("ix_skus_deleted_at"), "skus", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_index(
        "uix_skus_sku_code",
        "skus",
        ["sku_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uix_skus_variant_hash",
        "skus",
        ["variant_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "sku_attribute_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("attribute_value_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
            name=op.f("fk_sku_attribute_values_attribute_id_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_values.id"],
            name=op.f("fk_sku_attribute_values_attribute_value_id_attribute_values"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_sku_attribute_values_sku_id_skus"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_attribute_values")),
        sa.UniqueConstraint(
            "sku_id", "attribute_id", name="uix_sku_single_attribute_value"
        ),
    )
    op.create_index(
        "ix_sku_attr_val_lookup",
        "sku_attribute_values",
        ["attribute_value_id", "sku_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_attribute_id"),
        "sku_attribute_values",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_attribute_value_id"),
        "sku_attribute_values",
        ["attribute_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sku_attribute_values_sku_id"),
        "sku_attribute_values",
        ["sku_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sku_attribute_values_sku_id"), table_name="sku_attribute_values"
    )
    op.drop_index(
        op.f("ix_sku_attribute_values_attribute_value_id"),
        table_name="sku_attribute_values",
    )
    op.drop_index(
        op.f("ix_sku_attribute_values_attribute_id"), table_name="sku_attribute_values"
    )
    op.drop_index("ix_sku_attr_val_lookup", table_name="sku_attribute_values")
    op.drop_table("sku_attribute_values")
    op.drop_index(
        "uix_skus_variant_hash",
        table_name="skus",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uix_skus_sku_code",
        table_name="skus",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_deleted_at"), table_name="skus")
    op.drop_table("skus")
    op.drop_index(
        "uix_media_single_main_per_color",
        table_name="media_assets",
        postgresql_where=sa.text("role = 'MAIN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_media_assets_storage_object_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_product_id"), table_name="media_assets")
    op.drop_index("ix_media_assets_product_attr", table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_media_type"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_attribute_value_id"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(
        "uix_products_slug",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_products_title_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_index("ix_products_tags_gin", table_name="products", postgresql_using="gin")
    op.drop_index(op.f("ix_products_supplier_id"), table_name="products")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(
        "ix_products_sale_listing",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.drop_index(op.f("ix_products_primary_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_deleted_at"), table_name="products")
    op.drop_index(
        "ix_products_catalog_listing",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL AND is_visible = true"),
    )
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_index(
        "ix_products_attributes_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_table("products")
    op.drop_index("uix_cat_attr_rule", table_name="category_attribute_rules")
    op.drop_index(
        op.f("ix_category_attribute_rules_category_id"),
        table_name="category_attribute_rules",
    )
    op.drop_index(
        op.f("ix_category_attribute_rules_attribute_id"),
        table_name="category_attribute_rules",
    )
    op.drop_table("category_attribute_rules")
    op.drop_index("uix_attr_val_slug", table_name="attribute_values")
    op.drop_index("uix_attr_val_code", table_name="attribute_values")
    op.drop_index(op.f("ix_attribute_values_slug"), table_name="attribute_values")
    op.drop_index(op.f("ix_attribute_values_group_code"), table_name="attribute_values")
    op.drop_index(
        op.f("ix_attribute_values_attribute_id"), table_name="attribute_values"
    )
    op.drop_index(
        "ix_attr_val_value_i18n_gin",
        table_name="attribute_values",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_attr_val_search_aliases_gin",
        table_name="attribute_values",
        postgresql_using="gin",
    )
    op.drop_table("attribute_values")
    op.drop_table("suppliers")
    op.drop_index(
        "uix_categories_slug",
        table_name="categories",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_categories_sort_order"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index("ix_categories_level_sort", table_name="categories")
    op.drop_index(op.f("ix_categories_level"), table_name="categories")
    op.drop_index(
        "ix_categories_full_slug_ops",
        table_name="categories",
        postgresql_ops={"full_slug": "varchar_pattern_ops"},
    )
    op.drop_index(op.f("ix_categories_full_slug"), table_name="categories")
    op.drop_table("categories")
    op.drop_index("uix_brands_name", table_name="brands")
    op.drop_index(op.f("ix_brands_slug"), table_name="brands")
    op.drop_index(op.f("ix_brands_logo_file_id"), table_name="brands")
    op.drop_table("brands")
    op.drop_index("uix_attributes_slug", table_name="attributes")
    op.drop_index("uix_attributes_code", table_name="attributes")
    op.drop_index(
        "ix_attributes_name_i18n_gin", table_name="attributes", postgresql_using="gin"
    )
    op.drop_table("attributes")
    # ### end Alembic commands ###
