"""create IAM tables

Revision ID: f788d1919523
Revises: b7c8d9e0f1a2
Create Date: 2026-03-16 08:24:04.971591

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import MetaData  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f788d1919523"
down_revision: Union[str, Sequence[str], None] = "b7c8d9e0f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identities",
        sa.Column("id", sa.UUID(), nullable=False, comment="PK (UUIDv7)"),
        sa.Column(
            "type",
            sa.Enum(
                "LOCAL",
                "OIDC",
                name="identitytype",
                metadata=MetaData(),
                native_enum=False,
                length=10,
            ),
            nullable=False,
            comment="Authentication method: LOCAL or OIDC",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether identity can authenticate",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
        comment="Authentication identities (root entity for IAM)",
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "codename",
            sa.String(length=100),
            nullable=False,
            comment="Permission codename in resource:action format",
        ),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("codename", name=op.f("uq_permissions_codename")),
        comment="RBAC permissions (resource:action codenames)",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="System roles cannot be modified or deleted",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
        comment="RBAC role definitions",
    )
    op.create_table(
        "identity_roles",
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "assigned_by",
            sa.UUID(),
            nullable=True,
            comment="Identity ID of admin who assigned this role",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_identity_roles_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_identity_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "identity_id", "role_id", name=op.f("pk_identity_roles")
        ),
    )
    op.create_table(
        "linked_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_sub_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=320), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_linked_accounts_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_linked_accounts")),
        sa.UniqueConstraint(
            "provider", "provider_sub_id", name="uq_linked_accounts_provider_sub"
        ),
        comment="External OIDC provider accounts linked to identities",
    )
    op.create_index(
        op.f("ix_linked_accounts_identity_id"),
        "linked_accounts",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "local_credentials",
        sa.Column(
            "identity_id",
            sa.UUID(),
            nullable=False,
            comment="PK + FK → identities (Shared PK 1:1)",
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="Login email (unique across system)",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Argon2id (new) or Bcrypt (legacy) hash",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_local_credentials_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("identity_id", name=op.f("pk_local_credentials")),
        sa.UniqueConstraint("email", name=op.f("uq_local_credentials_email")),
        comment="Local auth credentials (email + password hash)",
    )
    op.create_table(
        "role_hierarchy",
        sa.Column("parent_role_id", sa.UUID(), nullable=False),
        sa.Column("child_role_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "parent_role_id != child_role_id",
            name=op.f("ck_role_hierarchy_ck_role_hierarchy_no_self_ref"),
        ),
        sa.ForeignKeyConstraint(
            ["child_role_id"],
            ["roles.id"],
            name=op.f("fk_role_hierarchy_child_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["roles.id"],
            name=op.f("fk_role_hierarchy_parent_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "parent_role_id", "child_role_id", name=op.f("pk_role_hierarchy")
        ),
        comment="Role inheritance: parent inherits all child permissions via CTE",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name=op.f("pk_role_permissions")
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column(
            "refresh_token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of opaque refresh token",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="Client IP at session creation",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="Client User-Agent",
        ),
        sa.Column(
            "is_revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Refresh token expiry (created_at + REFRESH_TOKEN_EXPIRE_DAYS)",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["identities.id"],
            name=op.f("fk_sessions_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint(
            "refresh_token_hash", name=op.f("uq_sessions_refresh_token_hash")
        ),
        comment="Authentication sessions with refresh token rotation",
    )
    op.create_index(
        "ix_sessions_identity_revoked",
        "sessions",
        ["identity_id", "is_revoked"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="PK + FK → identities (Shared PK 1:1)",
        ),
        sa.Column(
            "profile_email",
            sa.String(length=320),
            nullable=True,
            comment="Display email (may differ from login email in local_credentials)",
        ),
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["identities.id"],
            name=op.f("fk_users_id_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        comment="User PII (GDPR-isolated from auth data)",
    )
    op.create_table(
        "session_roles",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_session_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_roles_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "role_id", name=op.f("pk_session_roles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_roles")
    op.drop_table("users")
    op.drop_index("ix_sessions_identity_revoked", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("role_permissions")
    op.drop_table("role_hierarchy")
    op.drop_table("local_credentials")
    op.drop_index(op.f("ix_linked_accounts_identity_id"), table_name="linked_accounts")
    op.drop_table("linked_accounts")
    op.drop_table("identity_roles")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("identities")
    # ### end Alembic commands ###
