# tests/integration/modules/catalog/application/commands/test_create_brand.py
"""Integration tests for CreateBrandHandler — refactored to use InMemoryBlobStorage Fake."""

from dishka import AsyncContainer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.infrastructure.database.models.outbox import OutboxMessage
from src.modules.catalog.application.commands.create_brand import (
    CreateBrandCommand,
    CreateBrandHandler,
    LogoMetadata,
)
from src.modules.catalog.application.constants import raw_logo_key
from src.modules.catalog.domain.value_objects import MediaProcessingStatus
from src.modules.catalog.infrastructure.models import Brand as OrmBrand


async def test_create_brand_handler_without_logo(
    app_container: AsyncContainer, db_session: AsyncSession
):
    # Arrange
    async with app_container() as request_container:
        handler = await request_container.get(CreateBrandHandler)
        command = CreateBrandCommand(name="TestBrand", slug="testbrand", logo=None)

        # Act
        result = await handler.handle(command)

    # Assert
    assert result.brand_id is not None
    assert result.presigned_upload_url is None
    assert result.object_key is None

    # Verify in DB
    orm_brand = await db_session.get(OrmBrand, result.brand_id)
    assert orm_brand is not None
    assert orm_brand.slug == "testbrand"
    assert orm_brand.logo_status is None


async def test_create_brand_handler_with_logo(
    app_container: AsyncContainer, db_session: AsyncSession
):
    """Uses InMemoryBlobStorage Fake instead of patch.object + AsyncMock."""
    # Arrange & Act — InMemoryBlobStorage.generate_presigned_put_url returns
    # a deterministic URL based on object_name and content_type
    async with app_container() as request_container:
        handler = await request_container.get(CreateBrandHandler)

        command = CreateBrandCommand(
            name="TestBrandWithLogo",
            slug="testbrand-logo",
            logo=LogoMetadata(filename="logo.png", content_type="image/png"),
        )
        result = await handler.handle(command)

    # Assert — presigned URL generated by InMemoryBlobStorage Fake
    assert result.brand_id is not None
    expected_key = raw_logo_key(result.brand_id)
    assert result.object_key == expected_key
    assert result.presigned_upload_url is not None
    assert expected_key in result.presigned_upload_url
    assert "image/png" in result.presigned_upload_url

    # Verify in DB
    orm_brand = await db_session.get(OrmBrand, result.brand_id)
    assert orm_brand is not None
    assert orm_brand.logo_status == MediaProcessingStatus.PENDING_UPLOAD

    # Verify Outbox — BrandCreatedEvent recorded atomically
    outbox_result = await db_session.execute(
        select(OutboxMessage).where(
            OutboxMessage.aggregate_type == "Brand",
            OutboxMessage.aggregate_id == str(result.brand_id),
            OutboxMessage.event_type == "BrandCreatedEvent",
        )
    )
    outbox_row = outbox_result.scalar_one_or_none()
    assert outbox_row is not None, "BrandCreatedEvent not found in Outbox"
    assert outbox_row.payload["object_key"] == expected_key
    assert outbox_row.payload["content_type"] == "image/png"
