"""
Catalog domain events.

Events are emitted by Brand, Category, AttributeGroup, Attribute,
and AttributeFamily aggregates during business operations, serialized to JSON via
``dataclasses.asdict()``, and stored atomically in the Outbox table.
The infrastructure layer relays them to downstream consumers.

Typical usage:
    brand.add_domain_event(BrandLogoUploadInitiatedEvent(brand_id=brand.id, ...))

Note:
    Events are plain (non-frozen) dataclasses because ``DomainEvent``
    (the shared base class) is non-frozen and Python prohibits frozen
    subclasses of non-frozen parents. Events MUST be treated as
    immutable after construction — do not mutate event fields after
    ``__post_init__`` has run.
"""

import uuid
from dataclasses import dataclass
from typing import ClassVar

from src.shared.interfaces.entities import DomainEvent


@dataclass
class CatalogEvent(DomainEvent):
    """Intermediate base for all catalog domain events.

    Subclasses declare which UUID fields are required and which field
    supplies the ``aggregate_id`` via two class-level tuples:

    * ``_required_fields`` — field names that must not be ``None``.
    * ``_aggregate_id_field`` — the single field whose ``str()`` value
      is copied into ``aggregate_id`` when the caller does not set it
      explicitly.

    This eliminates the repetitive ``__post_init__`` boilerplate that
    was previously copy-pasted across every concrete event class.
    """

    # ClassVar so dataclasses ignores them; subclasses override via __init_subclass__
    _required_fields: ClassVar[tuple[str, ...]] = ()
    _aggregate_id_field: ClassVar[str] = ""

    # Provide non-empty defaults so DomainEvent.__init_subclass__ doesn't
    # reject CatalogEvent itself (concrete events override these).
    aggregate_type: str = "Catalog"
    event_type: str = "CatalogEvent"

    def __init_subclass__(
        cls,
        *,
        required_fields: tuple[str, ...] | None = None,
        aggregate_id_field: str | None = None,
        **kwargs: object,
    ) -> None:
        super().__init_subclass__(**kwargs)
        if required_fields is not None:
            cls._required_fields = required_fields
        if aggregate_id_field is not None:
            cls._aggregate_id_field = aggregate_id_field

        # Guard: concrete events must override event_type and aggregate_type.
        # Without this, a forgotten override silently inherits "CatalogEvent",
        # causing misrouted events in downstream consumers.
        if required_fields is not None:
            if cls.event_type == "CatalogEvent":
                raise TypeError(
                    f"{cls.__name__} must define its own 'event_type' "
                    f"(inherited default 'CatalogEvent' would misroute events)"
                )
            if cls.aggregate_type == "Catalog":
                raise TypeError(
                    f"{cls.__name__} must define its own 'aggregate_type' "
                    f"(inherited default 'Catalog' would misroute events)"
                )

    def __post_init__(self) -> None:
        cls_name = type(self).__name__
        for field_name in self._required_fields:
            if getattr(self, field_name) is None:
                raise ValueError(f"{field_name} is required for {cls_name}")
        if not self.aggregate_id and self._aggregate_id_field:
            self.aggregate_id = str(getattr(self, self._aggregate_id_field))


# ---------------------------------------------------------------------------
# Brand events
# ---------------------------------------------------------------------------


@dataclass
class BrandLogoUploadInitiatedEvent(
    CatalogEvent,
    required_fields=("brand_id",),
    aggregate_id_field="brand_id",
):
    """Emitted when a brand logo upload is initiated.

    The Storage module reacts by creating a ``StorageFile`` record
    and preparing the upload slot asynchronously.

    Attributes:
        brand_id: UUID of the brand initiating logo upload.
        object_key: S3 key where the client will upload the raw logo.
        content_type: Expected MIME type of the logo file.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoUploadInitiatedEvent"


@dataclass
class BrandLogoConfirmedEvent(
    CatalogEvent,
    required_fields=("brand_id",),
    aggregate_id_field="brand_id",
):
    """Emitted when a logo upload is confirmed and processing should begin.

    Generated by ``Brand.confirm_logo_upload()``. Triggers background
    image processing (resize, WebP conversion).

    Attributes:
        brand_id: UUID of the brand whose logo was confirmed.
    """

    brand_id: uuid.UUID | None = None
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoConfirmedEvent"


@dataclass
class BrandLogoProcessedEvent(
    CatalogEvent,
    required_fields=("brand_id",),
    aggregate_id_field="brand_id",
):
    """Emitted when logo processing completes successfully.

    Generated by ``Brand.complete_logo_processing()``. The Storage module
    reacts by registering the final processed file metadata.

    Attributes:
        brand_id: UUID of the brand whose logo was processed.
        object_key: Final S3 key of the processed logo.
        content_type: MIME type of the processed file.
        size_bytes: Size of the processed file in bytes.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    size_bytes: int = 0
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoProcessedEvent"


@dataclass
class BrandDeletedEvent(
    CatalogEvent,
    required_fields=("brand_id",),
    aggregate_id_field="brand_id",
):
    """Emitted when a brand is deleted."""

    brand_id: uuid.UUID | None = None
    aggregate_type: str = "Brand"
    event_type: str = "BrandDeletedEvent"


# ---------------------------------------------------------------------------
# Category events
# ---------------------------------------------------------------------------


@dataclass
class CategoryDeletedEvent(
    CatalogEvent,
    required_fields=("category_id",),
    aggregate_id_field="category_id",
):
    """Emitted when a category is deleted.

    Downstream consumers (e.g. search index) react by removing
    the category from their stores.
    """

    category_id: uuid.UUID | None = None
    slug: str = ""
    aggregate_type: str = "Category"
    event_type: str = "CategoryDeletedEvent"


# ---------------------------------------------------------------------------
# AttributeGroup events
# ---------------------------------------------------------------------------


@dataclass
class AttributeGroupCreatedEvent(
    CatalogEvent,
    required_fields=("group_id",),
    aggregate_id_field="group_id",
):
    """Emitted when a new attribute group is created."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupCreatedEvent"


@dataclass
class AttributeGroupUpdatedEvent(
    CatalogEvent,
    required_fields=("group_id",),
    aggregate_id_field="group_id",
):
    """Emitted when an attribute group is updated."""

    group_id: uuid.UUID | None = None
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupUpdatedEvent"


@dataclass
class AttributeGroupDeletedEvent(
    CatalogEvent,
    required_fields=("group_id",),
    aggregate_id_field="group_id",
):
    """Emitted when an attribute group is deleted."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupDeletedEvent"


# ---------------------------------------------------------------------------
# Attribute events
# ---------------------------------------------------------------------------


@dataclass
class AttributeCreatedEvent(
    CatalogEvent,
    required_fields=("attribute_id",),
    aggregate_id_field="attribute_id",
):
    """Emitted when a new attribute is created.

    Attributes:
        attribute_id: UUID of the newly created attribute.
        code: Machine-readable attribute code.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeCreatedEvent"


@dataclass
class AttributeUpdatedEvent(
    CatalogEvent,
    required_fields=("attribute_id",),
    aggregate_id_field="attribute_id",
):
    """Emitted when an attribute is updated.

    Attributes:
        attribute_id: UUID of the updated attribute.
    """

    attribute_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeUpdatedEvent"


@dataclass
class AttributeDeletedEvent(
    CatalogEvent,
    required_fields=("attribute_id",),
    aggregate_id_field="attribute_id",
):
    """Emitted when an attribute is deleted.

    Attributes:
        attribute_id: UUID of the deleted attribute.
        code: Code of the deleted attribute.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeDeletedEvent"


# ---------------------------------------------------------------------------
# AttributeValue events
# ---------------------------------------------------------------------------


@dataclass
class AttributeValueAddedEvent(
    CatalogEvent,
    required_fields=("attribute_id", "value_id"),
    aggregate_id_field="attribute_id",
):
    """Emitted when a new value is added to a dictionary attribute.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the newly added value.
        code: Machine-readable value code.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueAddedEvent"


@dataclass
class AttributeValueUpdatedEvent(
    CatalogEvent,
    required_fields=("attribute_id", "value_id"),
    aggregate_id_field="attribute_id",
):
    """Emitted when an attribute value is updated.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the updated value.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueUpdatedEvent"


@dataclass
class AttributeValueDeletedEvent(
    CatalogEvent,
    required_fields=("attribute_id", "value_id"),
    aggregate_id_field="attribute_id",
):
    """Emitted when an attribute value is deleted.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the deleted value.
        code: Code of the deleted value.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueDeletedEvent"


@dataclass
class AttributeValuesReorderedEvent(
    CatalogEvent,
    required_fields=("attribute_id",),
    aggregate_id_field="attribute_id",
):
    """Emitted when attribute values are bulk-reordered."""

    attribute_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValuesReorderedEvent"


# ---------------------------------------------------------------------------
# AttributeFamily events
# ---------------------------------------------------------------------------


@dataclass
class AttributeFamilyCreatedEvent(
    CatalogEvent,
    required_fields=("family_id",),
    aggregate_id_field="family_id",
):
    """Emitted when a new attribute family is created."""

    family_id: uuid.UUID | None = None
    code: str = ""
    parent_id: uuid.UUID | None = None
    aggregate_type: str = "AttributeFamily"
    event_type: str = "AttributeFamilyCreatedEvent"


@dataclass
class AttributeFamilyUpdatedEvent(
    CatalogEvent,
    required_fields=("family_id",),
    aggregate_id_field="family_id",
):
    """Emitted when an attribute family is updated."""

    family_id: uuid.UUID | None = None
    aggregate_type: str = "AttributeFamily"
    event_type: str = "AttributeFamilyUpdatedEvent"


@dataclass
class AttributeFamilyDeletedEvent(
    CatalogEvent,
    required_fields=("family_id",),
    aggregate_id_field="family_id",
):
    """Emitted when an attribute family is deleted."""

    family_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeFamily"
    event_type: str = "AttributeFamilyDeletedEvent"


# ---------------------------------------------------------------------------
# FamilyAttributeBinding events
# ---------------------------------------------------------------------------


@dataclass
class FamilyAttributeBindingCreatedEvent(
    CatalogEvent,
    required_fields=("binding_id",),
    aggregate_id_field="binding_id",
):
    """Emitted when an attribute is bound to a family."""

    family_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    binding_id: uuid.UUID | None = None
    aggregate_type: str = "FamilyAttributeBinding"
    event_type: str = "FamilyAttributeBindingCreatedEvent"


@dataclass
class FamilyAttributeBindingUpdatedEvent(
    CatalogEvent,
    required_fields=("binding_id",),
    aggregate_id_field="binding_id",
):
    """Emitted when a family-attribute binding is updated."""

    binding_id: uuid.UUID | None = None
    aggregate_type: str = "FamilyAttributeBinding"
    event_type: str = "FamilyAttributeBindingUpdatedEvent"


@dataclass
class FamilyAttributeBindingDeletedEvent(
    CatalogEvent,
    required_fields=("binding_id",),
    aggregate_id_field="binding_id",
):
    """Emitted when an attribute is unbound from a family."""

    family_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    binding_id: uuid.UUID | None = None
    aggregate_type: str = "FamilyAttributeBinding"
    event_type: str = "FamilyAttributeBindingDeletedEvent"


# ---------------------------------------------------------------------------
# FamilyAttributeExclusion events
# ---------------------------------------------------------------------------


@dataclass
class FamilyAttributeExclusionAddedEvent(
    CatalogEvent,
    required_fields=("exclusion_id",),
    aggregate_id_field="exclusion_id",
):
    """Emitted when an inherited attribute is excluded from a family."""

    family_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    exclusion_id: uuid.UUID | None = None
    aggregate_type: str = "FamilyAttributeExclusion"
    event_type: str = "FamilyAttributeExclusionAddedEvent"


@dataclass
class FamilyAttributeExclusionRemovedEvent(
    CatalogEvent,
    required_fields=("exclusion_id",),
    aggregate_id_field="exclusion_id",
):
    """Emitted when an attribute exclusion is removed from a family."""

    family_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    exclusion_id: uuid.UUID | None = None
    aggregate_type: str = "FamilyAttributeExclusion"
    event_type: str = "FamilyAttributeExclusionRemovedEvent"


# ---------------------------------------------------------------------------
# ProductMedia events
# ---------------------------------------------------------------------------


@dataclass
class ProductMediaConfirmedEvent(
    CatalogEvent,
    required_fields=("media_id",),
    aggregate_id_field="media_id",
):
    """Emitted when a media upload is confirmed — triggers AI processing."""

    media_id: uuid.UUID | None = None
    product_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    aggregate_type: str = "ProductMedia"
    event_type: str = "ProductMediaConfirmedEvent"


@dataclass
class ProductMediaProcessedEvent(
    CatalogEvent,
    required_fields=("media_id",),
    aggregate_id_field="media_id",
):
    """Emitted when AI processing completes for a media asset."""

    media_id: uuid.UUID | None = None
    product_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    size_bytes: int = 0
    aggregate_type: str = "ProductMedia"
    event_type: str = "ProductMediaProcessedEvent"


# ---------------------------------------------------------------------------
# Product events
# ---------------------------------------------------------------------------


@dataclass
class ProductCreatedEvent(
    CatalogEvent,
    required_fields=("product_id",),
    aggregate_id_field="product_id",
):
    """Emitted when a new product is created."""

    product_id: uuid.UUID | None = None
    slug: str = ""
    aggregate_type: str = "Product"
    event_type: str = "ProductCreatedEvent"


@dataclass
class ProductStatusChangedEvent(
    CatalogEvent,
    required_fields=("product_id",),
    aggregate_id_field="product_id",
):
    """Emitted when a product's status transitions."""

    product_id: uuid.UUID | None = None
    old_status: str = ""
    new_status: str = ""
    aggregate_type: str = "Product"
    event_type: str = "ProductStatusChangedEvent"


@dataclass
class ProductUpdatedEvent(
    CatalogEvent,
    required_fields=("product_id",),
    aggregate_id_field="product_id",
):
    """Emitted when product fields are updated via partial update."""

    product_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "ProductUpdatedEvent"


# ---------------------------------------------------------------------------
# ProductVariant events
# ---------------------------------------------------------------------------


@dataclass
class VariantAddedEvent(
    CatalogEvent,
    required_fields=("product_id", "variant_id"),
    aggregate_id_field="product_id",
):
    """Emitted when a new variant is added to a product."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "VariantAddedEvent"


@dataclass
class VariantDeletedEvent(
    CatalogEvent,
    required_fields=("product_id", "variant_id"),
    aggregate_id_field="product_id",
):
    """Emitted when a variant is soft-deleted from a product."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "VariantDeletedEvent"


# ---------------------------------------------------------------------------
# SKU events
# ---------------------------------------------------------------------------


@dataclass
class SKUAddedEvent(
    CatalogEvent,
    required_fields=("product_id", "variant_id", "sku_id"),
    aggregate_id_field="product_id",
):
    """Emitted when a new SKU is added to a product variant."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    sku_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "SKUAddedEvent"


@dataclass
class SKUDeletedEvent(
    CatalogEvent,
    required_fields=("product_id", "variant_id", "sku_id"),
    aggregate_id_field="product_id",
):
    """Emitted when a SKU is soft-deleted from a product variant."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    sku_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "SKUDeletedEvent"
