"""
Catalog domain events.

Events are emitted by Brand, Category, AttributeGroup, and Attribute
aggregates during business operations, serialized to JSON via
``dataclasses.asdict()``, and stored atomically in the Outbox table.
The infrastructure layer relays them to downstream consumers.

Typical usage:
    brand.add_domain_event(BrandLogoUploadInitiatedEvent(brand_id=brand.id, ...))

Note:
    DomainEvent (the shared base class) is a non-frozen dataclass, so
    Python prohibits frozen subclasses. Instead we use a
    ``_ImmutableAfterInit`` mixin that locks field assignment after
    ``__post_init__`` has run, providing runtime immutability without
    violating the inheritance constraint.
"""

import uuid
from dataclasses import dataclass

from src.shared.interfaces.entities import DomainEvent

# ---------------------------------------------------------------------------
# DDD-02: Immutability mixin for domain events
# ---------------------------------------------------------------------------


class _ImmutableAfterInit:
    """Mixin that freezes dataclass instances after ``__post_init__`` completes.

    Works with the standard ``@dataclass`` decorator. The ``__post_init__``
    method in subclasses must call ``super().__post_init__()`` **last** (or
    rely on MRO if using multiple inheritance). After ``_frozen`` is set to
    ``True``, any attribute assignment or deletion raises ``AttributeError``.
    """

    _frozen: bool = False

    def __setattr__(self, name: str, value: object) -> None:
        if self._frozen and name != "_domain_events":
            raise AttributeError(
                f"Cannot set attribute '{name}' on frozen event {type(self).__name__}"
            )
        super().__setattr__(name, value)

    def __delattr__(self, name: str) -> None:
        if self._frozen:
            raise AttributeError(
                f"Cannot delete attribute '{name}' on frozen event "
                f"{type(self).__name__}"
            )
        super().__delattr__(name)


def _freeze(event: _ImmutableAfterInit) -> None:
    """Freeze the event instance after post-init logic has completed."""
    object.__setattr__(event, "_frozen", True)


@dataclass
class BrandLogoUploadInitiatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a brand logo upload is initiated.

    The Storage module reacts by creating a ``StorageFile`` record
    and preparing the upload slot asynchronously.

    Attributes:
        brand_id: UUID of the brand initiating logo upload.
        object_key: S3 key where the client will upload the raw logo.
        content_type: Expected MIME type of the logo file.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoUploadInitiatedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandLogoUploadInitiatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)
        _freeze(self)


@dataclass
class BrandLogoConfirmedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a logo upload is confirmed and processing should begin.

    Generated by ``Brand.confirm_logo_upload()``. Triggers background
    image processing (resize, WebP conversion).

    Attributes:
        brand_id: UUID of the brand whose logo was confirmed.
    """

    brand_id: uuid.UUID | None = None
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoConfirmedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandLogoConfirmedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)
        _freeze(self)


@dataclass
class BrandLogoProcessedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when logo processing completes successfully.

    Generated by ``Brand.complete_logo_processing()``. The Storage module
    reacts by registering the final processed file metadata.

    Attributes:
        brand_id: UUID of the brand whose logo was processed.
        object_key: Final S3 key of the processed logo.
        content_type: MIME type of the processed file.
        size_bytes: Size of the processed file in bytes.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    size_bytes: int = 0
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoProcessedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandLogoProcessedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# AttributeGroup events
# ---------------------------------------------------------------------------


@dataclass
class AttributeGroupCreatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new attribute group is created."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupCreatedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)
        _freeze(self)


@dataclass
class AttributeGroupUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute group is updated."""

    group_id: uuid.UUID | None = None
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupUpdatedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)
        _freeze(self)


@dataclass
class AttributeGroupDeletedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute group is deleted."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupDeletedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupDeletedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# Attribute events
# ---------------------------------------------------------------------------


@dataclass
class AttributeCreatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new attribute is created.

    Attributes:
        attribute_id: UUID of the newly created attribute.
        code: Machine-readable attribute code.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeCreatedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


@dataclass
class AttributeUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute is updated.

    Attributes:
        attribute_id: UUID of the updated attribute.
    """

    attribute_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeUpdatedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


@dataclass
class AttributeDeletedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute is deleted.

    Attributes:
        attribute_id: UUID of the deleted attribute.
        code: Code of the deleted attribute.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeDeletedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeDeletedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# AttributeValue events
# ---------------------------------------------------------------------------


@dataclass
class AttributeValueAddedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new value is added to a dictionary attribute.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the newly added value.
        code: Machine-readable value code.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueAddedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeValueAddedEvent")
        if self.value_id is None:
            raise ValueError("value_id is required for AttributeValueAddedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


@dataclass
class AttributeValueUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute value is updated.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the updated value.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueUpdatedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeValueUpdatedEvent")
        if self.value_id is None:
            raise ValueError("value_id is required for AttributeValueUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


@dataclass
class AttributeValueDeletedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when an attribute value is deleted.

    Attributes:
        attribute_id: UUID of the parent attribute.
        value_id: UUID of the deleted value.
        code: Code of the deleted value.
    """

    attribute_id: uuid.UUID | None = None
    value_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValueDeletedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeValueDeletedEvent")
        if self.value_id is None:
            raise ValueError("value_id is required for AttributeValueDeletedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# CategoryAttributeBinding events
# ---------------------------------------------------------------------------


@dataclass
class CategoryAttributeBindingCreatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a category-attribute binding is created."""

    category_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    binding_id: uuid.UUID | None = None
    aggregate_type: str = "CategoryAttributeBinding"
    event_type: str = "CategoryAttributeBindingCreatedEvent"

    def __post_init__(self) -> None:
        if self.binding_id is None:
            raise ValueError(
                "binding_id is required for CategoryAttributeBindingCreatedEvent"
            )
        if self.category_id is None:
            raise ValueError(
                "category_id is required for CategoryAttributeBindingCreatedEvent"
            )
        if self.attribute_id is None:
            raise ValueError(
                "attribute_id is required for CategoryAttributeBindingCreatedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.binding_id)
        _freeze(self)


@dataclass
class CategoryAttributeBindingUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a category-attribute binding is updated."""

    binding_id: uuid.UUID | None = None
    aggregate_type: str = "CategoryAttributeBinding"
    event_type: str = "CategoryAttributeBindingUpdatedEvent"

    def __post_init__(self) -> None:
        if self.binding_id is None:
            raise ValueError(
                "binding_id is required for CategoryAttributeBindingUpdatedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.binding_id)
        _freeze(self)


@dataclass
class CategoryAttributeBindingDeletedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a category-attribute binding is deleted."""

    category_id: uuid.UUID | None = None
    attribute_id: uuid.UUID | None = None
    binding_id: uuid.UUID | None = None
    aggregate_type: str = "CategoryAttributeBinding"
    event_type: str = "CategoryAttributeBindingDeletedEvent"

    def __post_init__(self) -> None:
        if self.binding_id is None:
            raise ValueError(
                "binding_id is required for CategoryAttributeBindingDeletedEvent"
            )
        if self.category_id is None:
            raise ValueError(
                "category_id is required for CategoryAttributeBindingDeletedEvent"
            )
        if self.attribute_id is None:
            raise ValueError(
                "attribute_id is required for CategoryAttributeBindingDeletedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.binding_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# ProductMedia events
# ---------------------------------------------------------------------------


@dataclass
class ProductMediaConfirmedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a media upload is confirmed -- triggers AI processing."""

    media_id: uuid.UUID | None = None
    product_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    aggregate_type: str = "ProductMedia"
    event_type: str = "ProductMediaConfirmedEvent"

    def __post_init__(self) -> None:
        if self.media_id is None:
            raise ValueError("media_id is required for ProductMediaConfirmedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.media_id)
        _freeze(self)


@dataclass
class ProductMediaProcessedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when AI processing completes for a media asset."""

    media_id: uuid.UUID | None = None
    product_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    size_bytes: int = 0
    aggregate_type: str = "ProductMedia"
    event_type: str = "ProductMediaProcessedEvent"

    def __post_init__(self) -> None:
        if self.media_id is None:
            raise ValueError("media_id is required for ProductMediaProcessedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.media_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# Product events
# ---------------------------------------------------------------------------


@dataclass
class ProductCreatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new product is created."""

    product_id: uuid.UUID | None = None
    slug: str = ""
    aggregate_type: str = "Product"
    event_type: str = "ProductCreatedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for ProductCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


@dataclass
class ProductUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when product fields are updated."""

    product_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "ProductUpdatedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for ProductUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


@dataclass
class ProductStatusChangedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a product's status transitions."""

    product_id: uuid.UUID | None = None
    old_status: str = ""
    new_status: str = ""
    aggregate_type: str = "Product"
    event_type: str = "ProductStatusChangedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for ProductStatusChangedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# Product Variant & SKU events
# ---------------------------------------------------------------------------


@dataclass
class VariantAddedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new variant is added to a product."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "VariantAddedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for VariantAddedEvent")
        if self.variant_id is None:
            raise ValueError("variant_id is required for VariantAddedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


@dataclass
class VariantRemovedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a variant is removed (soft-deleted) from a product."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "VariantRemovedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for VariantRemovedEvent")
        if self.variant_id is None:
            raise ValueError("variant_id is required for VariantRemovedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


@dataclass
class SKUAddedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a new SKU is added to a product variant."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    sku_id: uuid.UUID | None = None
    sku_code: str = ""
    aggregate_type: str = "Product"
    event_type: str = "SKUAddedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for SKUAddedEvent")
        if self.sku_id is None:
            raise ValueError("sku_id is required for SKUAddedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


@dataclass
class SKURemovedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when a SKU is removed (soft-deleted) from a product."""

    product_id: uuid.UUID | None = None
    variant_id: uuid.UUID | None = None
    sku_id: uuid.UUID | None = None
    aggregate_type: str = "Product"
    event_type: str = "SKURemovedEvent"

    def __post_init__(self) -> None:
        if self.product_id is None:
            raise ValueError("product_id is required for SKURemovedEvent")
        if self.sku_id is None:
            raise ValueError("sku_id is required for SKURemovedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.product_id)
        _freeze(self)


# ---------------------------------------------------------------------------
# Bulk operation events
# ---------------------------------------------------------------------------


@dataclass
class AttributeValuesReorderedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when attribute values are bulk-reordered."""

    attribute_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeValuesReorderedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError(
                "attribute_id is required for AttributeValuesReorderedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
        _freeze(self)


@dataclass
class CategoryBindingsReorderedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when category-attribute bindings are bulk-reordered."""

    category_id: uuid.UUID | None = None
    aggregate_type: str = "Category"
    event_type: str = "CategoryBindingsReorderedEvent"

    def __post_init__(self) -> None:
        if self.category_id is None:
            raise ValueError(
                "category_id is required for CategoryBindingsReorderedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.category_id)
        _freeze(self)


@dataclass
class RequirementLevelsUpdatedEvent(_ImmutableAfterInit, DomainEvent):
    """Emitted when requirement levels are bulk-updated."""

    category_id: uuid.UUID | None = None
    aggregate_type: str = "Category"
    event_type: str = "RequirementLevelsUpdatedEvent"

    def __post_init__(self) -> None:
        if self.category_id is None:
            raise ValueError(
                "category_id is required for RequirementLevelsUpdatedEvent"
            )
        if not self.aggregate_id:
            self.aggregate_id = str(self.category_id)
        _freeze(self)
