"""
Catalog domain events.

Events are emitted by Brand, Category, AttributeGroup, and Attribute
aggregates during business operations, serialized to JSON via
``dataclasses.asdict()``, and stored atomically in the Outbox table.
The infrastructure layer relays them to downstream consumers.

Typical usage:
    brand.add_domain_event(BrandCreatedEvent(brand_id=brand.id, ...))
"""

import uuid
from dataclasses import dataclass

from src.shared.interfaces.entities import DomainEvent


@dataclass
class BrandCreatedEvent(DomainEvent):
    """Emitted when a brand is created with a logo upload request.

    The Storage module reacts by creating a ``StorageFile`` record
    and preparing the upload slot asynchronously.

    Attributes:
        brand_id: UUID of the newly created brand.
        object_key: S3 key where the client will upload the raw logo.
        content_type: Expected MIME type of the logo file.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    aggregate_type: str = "Brand"
    event_type: str = "BrandCreatedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)


@dataclass
class BrandLogoConfirmedEvent(DomainEvent):
    """Emitted when a logo upload is confirmed and processing should begin.

    Generated by ``Brand.confirm_logo_upload()``. Triggers background
    image processing (resize, WebP conversion).

    Attributes:
        brand_id: UUID of the brand whose logo was confirmed.
    """

    brand_id: uuid.UUID | None = None
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoConfirmedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandLogoConfirmedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)


@dataclass
class BrandLogoProcessedEvent(DomainEvent):
    """Emitted when logo processing completes successfully.

    Generated by ``Brand.complete_logo_processing()``. The Storage module
    reacts by registering the final processed file metadata.

    Attributes:
        brand_id: UUID of the brand whose logo was processed.
        object_key: Final S3 key of the processed logo.
        content_type: MIME type of the processed file.
        size_bytes: Size of the processed file in bytes.
    """

    brand_id: uuid.UUID | None = None
    object_key: str = ""
    content_type: str = ""
    size_bytes: int = 0
    aggregate_type: str = "Brand"
    event_type: str = "BrandLogoProcessedEvent"

    def __post_init__(self) -> None:
        if self.brand_id is None:
            raise ValueError("brand_id is required for BrandLogoProcessedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.brand_id)


# ---------------------------------------------------------------------------
# AttributeGroup events
# ---------------------------------------------------------------------------


@dataclass
class AttributeGroupCreatedEvent(DomainEvent):
    """Emitted when a new attribute group is created."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupCreatedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)


@dataclass
class AttributeGroupUpdatedEvent(DomainEvent):
    """Emitted when an attribute group is updated."""

    group_id: uuid.UUID | None = None
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupUpdatedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)


@dataclass
class AttributeGroupDeletedEvent(DomainEvent):
    """Emitted when an attribute group is deleted."""

    group_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "AttributeGroup"
    event_type: str = "AttributeGroupDeletedEvent"

    def __post_init__(self) -> None:
        if self.group_id is None:
            raise ValueError("group_id is required for AttributeGroupDeletedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.group_id)


# ---------------------------------------------------------------------------
# Attribute events
# ---------------------------------------------------------------------------


@dataclass
class AttributeCreatedEvent(DomainEvent):
    """Emitted when a new attribute is created.

    Attributes:
        attribute_id: UUID of the newly created attribute.
        code: Machine-readable attribute code.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeCreatedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeCreatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)


@dataclass
class AttributeUpdatedEvent(DomainEvent):
    """Emitted when an attribute is updated.

    Attributes:
        attribute_id: UUID of the updated attribute.
    """

    attribute_id: uuid.UUID | None = None
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeUpdatedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeUpdatedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)


@dataclass
class AttributeDeletedEvent(DomainEvent):
    """Emitted when an attribute is deleted.

    Attributes:
        attribute_id: UUID of the deleted attribute.
        code: Code of the deleted attribute.
    """

    attribute_id: uuid.UUID | None = None
    code: str = ""
    aggregate_type: str = "Attribute"
    event_type: str = "AttributeDeletedEvent"

    def __post_init__(self) -> None:
        if self.attribute_id is None:
            raise ValueError("attribute_id is required for AttributeDeletedEvent")
        if not self.aggregate_id:
            self.aggregate_id = str(self.attribute_id)
